using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using MomenMedmSys.Core.Entities;
using MomenMedmSys.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace MomenMedmSys.Data
{
    public static class DatabaseSeeder
    {
        private static void Log(string msg)
        {
            try { File.AppendAllText("app_error.log", $"[{DateTime.Now:yyyy-MM-dd HH:mm:ss}] {msg}\n"); }
            catch { }
        }

        public static async Task<bool> SeedAsync(IServiceProvider serviceProvider)
        {
            try
            {
                using var scope = serviceProvider.CreateScope();
                var ctx = scope.ServiceProvider.GetRequiredService<MedMsysDbContext>();
                Log("Applying database migrations...");
                await ctx.Database.MigrateAsync();
                Log("Migrations applied successfully");

                // Verify Licenses table has required columns
                try
                {
                    var conn = ctx.Database.GetDbConnection();
                    await conn.OpenAsync();
                    using var cmd = conn.CreateCommand();
                    // Use MySQL information_schema for column verification
                    cmd.CommandText = @"
                        SELECT COLUMN_NAME 
                        FROM INFORMATION_SCHEMA.COLUMNS 
                        WHERE TABLE_SCHEMA = DATABASE() 
                        AND TABLE_NAME = 'Licenses'";
                    using var reader = await cmd.ExecuteReaderAsync();
                    var cols = new System.Collections.Generic.HashSet<string>(StringComparer.OrdinalIgnoreCase);
                    while (await reader.ReadAsync())
                    {
                        cols.Add(reader.GetString(0));
                    }
                    var required = new[] { "HospitalName", "AdministratorName", "LicenseNumber" };
                    var missing = required.Where(c => !cols.Contains(c)).ToArray();
                    if (missing.Any())
                    {
                        Log($"WARNING: Missing columns in Licenses: {string.Join(", ", missing)}");
                        Log("Attempting to apply pending migrations...");
                        // List pending migrations
                        var pending = await ctx.Database.GetPendingMigrationsAsync();
                        var pendingList = pending.ToList();
                        if (pendingList.Any())
                        {
                            Log($"Pending migrations: {string.Join(", ", pendingList)}");
                            foreach (var m in pendingList)
                            {
                                Log($"Applying migration: {m}");
                                await ctx.Database.MigrateAsync();
                                break; // MigrateAsync applies all, just log
                            }
                        }
                        else
                        {
                            Log("No pending migrations found via GetPendingMigrationsAsync()");
                        }
                    }
                    else
                    {
                        Log($"Licenses table columns verified: {string.Join(", ", cols.OrderBy(c => c))}");
                    }
                    await conn.CloseAsync();
                }
                catch (Exception ex2)
                {
                    Log($"[SchemaCheck] Failed: {ex2.GetType().Name}: {ex2.Message}");
                }

                bool hasDevices = await ctx.MedicalDevices.AnyAsync();
                bool hasAdmin = await ctx.StaffMembers.AnyAsync(s => s.Username == "admin");

                if (hasDevices && hasAdmin)
                {
                    Log("Data already exists, skipping seed");
                    return false;
                }

                // Seed in order with proper relationships
                await SeedBasicDataAsync(ctx, hasDevices, hasAdmin);
                Log("Data seeded successfully");
                return true;
            }
            catch (Exception ex)
            {
                Log($"[Seeder] Failed: {ex.GetType().Name}: {ex.Message}\n{ex.StackTrace}");
                return false;
            }
        }

        private static async Task SeedBasicDataAsync(MedMsysDbContext ctx, bool skipDevices, bool skipAdmin)
        {
            var now = DateTime.Now;

            // ═══════════════════════════════════════════
            // 1. DEPARTMENTS (12 hospital departments)
            // ═══════════════════════════════════════════
            if (!skipDevices)
            {
            ctx.Departments.AddRange(new[]
            {
                new Department { Id = 1, DepartmentCode = "RAD", Name = "Radiology", Manager = "Dr. Ahmed Hassan", Building = "Main", Floor = "1", Budget = 1500000, CreatedAt = now, IsActive = true },
                new Department { Id = 2, DepartmentCode = "ICU", Name = "Intensive Care Unit", Manager = "Dr. Fatima Mohamed", Building = "Main", Floor = "2", Budget = 2000000, CreatedAt = now, IsActive = true },
                new Department { Id = 3, DepartmentCode = "LAB", Name = "Central Laboratory", Manager = "Dr. Sara Ali", Building = "Annex", Floor = "1", Budget = 800000, CreatedAt = now, IsActive = true },
                new Department { Id = 4, DepartmentCode = "ER", Name = "Emergency Room", Manager = "Dr. Khalid Omer", Building = "Main", Floor = "Ground", Budget = 1200000, CreatedAt = now, IsActive = true },
                new Department { Id = 5, DepartmentCode = "OR", Name = "Operating Theatre", Manager = "Dr. Mona Ibrahim", Building = "Main", Floor = "3", Budget = 1800000, CreatedAt = now, IsActive = true },
                new Department { Id = 6, DepartmentCode = "CSSD", Name = "Sterilization (CSSD)", Manager = "Eng. Huda Yousif", Building = "Main", Floor = "1", Budget = 500000, CreatedAt = now, IsActive = true },
                new Department { Id = 7, DepartmentCode = "PHY", Name = "Physiotherapy", Manager = "Dr. Amira Eltayeb", Building = "Annex", Floor = "2", Budget = 400000, CreatedAt = now, IsActive = true },
                new Department { Id = 8, DepartmentCode = "DIA", Name = "Dialysis Unit", Manager = "Dr. Yasser Hamad", Building = "Annex", Floor = "1", Budget = 1200000, CreatedAt = now, IsActive = true },
                new Department { Id = 9, DepartmentCode = "NUR", Name = "Neonatal ICU (NICU)", Manager = "Dr. Nisreen Abdalla", Building = "Main", Floor = "2", Budget = 900000, CreatedAt = now, IsActive = true },
                new Department { Id = 10, DepartmentCode = "ANES", Name = "Anesthesiology", Manager = "Dr. Tariq Salih", Building = "Main", Floor = "3", Budget = 700000, CreatedAt = now, IsActive = true },
                new Department { Id = 11, DepartmentCode = "OPD", Name = "Outpatient Department", Manager = "Dr. Rehab Osman", Building = "Annex", Floor = "Ground", Budget = 300000, CreatedAt = now, IsActive = true },
                new Department { Id = 12, DepartmentCode = "BIO", Name = "Biomedical Engineering", Manager = "Eng. Mustafa Ahmed", Building = "Basement", Floor = "B1", Budget = 600000, CreatedAt = now, IsActive = true },
            });
            await ctx.SaveChangesAsync();
            }

            // ═══════════════════════════════════════════
            // 2. ADMIN USER
            // ═══════════════════════════════════════════
            if (!skipAdmin)
            {
                // Use BCrypt for secure password hashing
                var adminPasswordHash = BCrypt.Net.BCrypt.HashPassword("Admin@123");

                ctx.StaffMembers.Add(new StaffMember
                {
                    Id = 1,
                    EmployeeId = "EMP-ADMIN",
                    FirstName = "System",
                    LastName = "Administrator",
                    Email = "admin@mensystems.com",
                    Phone = "+249 124 349 024",
                    Role = StaffRole.Administrator,
                    SubRole = "System Administrator",
                    Department = "Biomedical Engineering",
                    JobTitle = "System Administrator",
                    Username = "admin",
                    PasswordHash = adminPasswordHash,
                    IsActiveAccount = true,
                    IsLocked = false,
                    FailedLoginAttempts = 0,
                    HireDate = now,
                    CanManageDevices = true,
                    CanManageMaintenance = true,
                    CanManageCalibration = true,
                    CanManageSpareParts = true,
                    CanViewReports = true,
                    CanManageNetworkDevices = true,
                    CanManageStaff = true,
                    CanAccessAdminPanel = true,
                    CreatedAt = now,
                    IsActive = true
                });
                await ctx.SaveChangesAsync();
            }

            // ═══════════════════════════════════════════
            // 3. SUPPLIERS (8 regional & international)
            // ═══════════════════════════════════════════
            if (!skipDevices)
            {
            ctx.Suppliers.AddRange(new[]
            {
                new Supplier { Id = 1, SupplierCode = "SUP-001", CompanyName = "Siemens Healthineers", ContactPerson = "Karim Mansour", Email = "k.mansour@siemens-healthineers.com", Phone = "+20 2 3760 8000", City = "Cairo", Country = "Egypt", Rating = 5, IsApproved = true, LeadTimeDays = 45, CreatedAt = now, IsActive = true },
                new Supplier { Id = 2, SupplierCode = "SUP-002", CompanyName = "GE Healthcare", ContactPerson = "Omar Khalil", Email = "omar.khalil@ge.com", Phone = "+971 4 818 8800", City = "Dubai", Country = "UAE", Rating = 5, IsApproved = true, LeadTimeDays = 60, CreatedAt = now, IsActive = true },
                new Supplier { Id = 3, SupplierCode = "SUP-003", CompanyName = "Mindray Medical", ContactPerson = "Li Wei", Email = "li.wei@mindray.com", Phone = "+86 755 8188 8888", City = "Shenzhen", Country = "China", Rating = 4, IsApproved = true, LeadTimeDays = 30, CreatedAt = now, IsActive = true },
                new Supplier { Id = 4, SupplierCode = "SUP-004", CompanyName = "Philips Healthcare", ContactPerson = "Nadia Soliman", Email = "nadia.soliman@philips.com", Phone = "+20 2 2480 9000", City = "Cairo", Country = "Egypt", Rating = 5, IsApproved = true, LeadTimeDays = 45, CreatedAt = now, IsActive = true },
                new Supplier { Id = 5, SupplierCode = "SUP-005", CompanyName = "Dräger Medical", ContactPerson = "Hans Mueller", Email = "h.mueller@draeger.com", Phone = "+49 451 882 0", City = "Lübeck", Country = "Germany", Rating = 5, IsApproved = true, LeadTimeDays = 50, CreatedAt = now, IsActive = true },
                new Supplier { Id = 6, SupplierCode = "SUP-006", CompanyName = "Fresenius Medical Care", ContactPerson = "Youssef Taha", Email = "youssef.taha@fresenius.com", Phone = "+20 2 3335 4000", City = "Cairo", Country = "Egypt", Rating = 4, IsApproved = true, LeadTimeDays = 35, CreatedAt = now, IsActive = true },
                new Supplier { Id = 7, SupplierCode = "SUP-007", CompanyName = "MedTech Sudan", ContactPerson = "Eng. Ibrahim Hassan", Email = "info@medtechsd.sd", Phone = "+249 183 777 123", City = "Khartoum", Country = "Sudan", Rating = 4, IsApproved = true, LeadTimeDays = 14, CreatedAt = now, IsActive = true },
                new Supplier { Id = 8, SupplierCode = "SUP-008", CompanyName = "Olympus Medical", ContactPerson = "Takeshi Yamamoto", Email = "t.yamamoto@olympus.com", Phone = "+81 3 6436 5100", City = "Tokyo", Country = "Japan", Rating = 5, IsApproved = true, LeadTimeDays = 55, CreatedAt = now, IsActive = true },
            });
            await ctx.SaveChangesAsync();

            // ═══════════════════════════════════════════
            // 4. MEDICAL DEVICES (35 devices across 12 departments)
            // ═══════════════════════════════════════════
            ctx.MedicalDevices.AddRange(new[]
            {
                // ─── Radiology ───
                new MedicalDevice { Id = 1, DeviceCode = "RAD-XR-001", DeviceName = "Siemens Multix Select DR", Manufacturer = "Siemens Healthineers", Model = "Multix Select DR", SerialNumber = "SH-XR-2021-0045", Category = "Digital X-Ray", PurchaseDate = new DateTime(2021,3,15), PurchasePrice = 120000m, SupplierId = 1, SupplierName = "Siemens Healthineers", WarrantyExpiryDate = new DateTime(2026,3,15), DepartmentId = 1, Department = "Radiology", Building = "Main", Floor = "1", Room = "XR-101", AssignedTo = "Tech. Mohamed Abdallah", TechnicalSpecs = "500mA, 150kV, AEC", PowerRequirements = "380V 3-Phase", RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.High, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 2, DeviceCode = "RAD-CT-002", DeviceName = "GE Optima CT520", Manufacturer = "GE Healthcare", Model = "Optima CT520", SerialNumber = "GE-CT-2020-1122", Category = "CT Scanner", PurchaseDate = new DateTime(2020,6,10), PurchasePrice = 450000m, SupplierId = 2, SupplierName = "GE Healthcare", WarrantyExpiryDate = new DateTime(2025,6,10), DepartmentId = 1, Department = "Radiology", Building = "Main", Floor = "Ground", Room = "CT-Suite", AssignedTo = "Dr. Ahmed Hassan", TechnicalSpecs = "16-slice, 0.625mm, 140kV", PowerRequirements = "400V 3-Phase 80A", RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.High, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 3, DeviceCode = "RAD-US-003", DeviceName = "Mindray DC-80 Ultrasound", Manufacturer = "Mindray", Model = "DC-80", SerialNumber = "MR-US-2022-0389", Category = "Ultrasound", PurchaseDate = new DateTime(2022,9,20), PurchasePrice = 85000m, SupplierId = 3, SupplierName = "Mindray Medical", WarrantyExpiryDate = new DateTime(2027,9,20), DepartmentId = 1, Department = "Radiology", Building = "Main", Floor = "1", Room = "US-105", AssignedTo = "Dr. Layla Mustafa", TechnicalSpecs = "4D Doppler, Convex/Linear probes", PowerRequirements = "220V AC", RequiresCalibration = false, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Medium, CreatedAt = now, IsActive = true },

                // ─── ICU ───
                new MedicalDevice { Id = 4, DeviceCode = "ICU-VM-004", DeviceName = "Dräger Evita V500 Ventilator", Manufacturer = "Dräger", Model = "Evita V500", SerialNumber = "DR-VM-2023-0567", Category = "Mechanical Ventilator", PurchaseDate = new DateTime(2023,1,8), PurchasePrice = 42000m, SupplierId = 5, SupplierName = "Dräger Medical", WarrantyExpiryDate = new DateTime(2028,1,8), DepartmentId = 2, Department = "Intensive Care Unit", Building = "Main", Floor = "2", Room = "ICU-201", AssignedTo = "Dr. Fatima Mohamed", TechnicalSpecs = "Volume/Pressure/PRVC, O2 21-100%", PowerRequirements = "220V AC + Battery Backup", RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Critical, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 5, DeviceCode = "ICU-PM-005", DeviceName = "Philips IntelliVue MX800", Manufacturer = "Philips Healthcare", Model = "IntelliVue MX800", SerialNumber = "PH-PM-2023-0890", Category = "Patient Monitor", PurchaseDate = new DateTime(2023,4,15), PurchasePrice = 25000m, SupplierId = 4, SupplierName = "Philips Healthcare", WarrantyExpiryDate = new DateTime(2028,4,15), DepartmentId = 2, Department = "Intensive Care Unit", Building = "Main", Floor = "2", Room = "ICU-202", AssignedTo = "Nurse Hala Yousif", TechnicalSpecs = "12-lead ECG, SpO2, NIBP, IBP, EtCO2, Temp", PowerRequirements = "100-240V AC + Battery", RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Critical, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 6, DeviceCode = "ICU-IP-006", DeviceName = "B. Braun Infusomat Space", Manufacturer = "B. Braun", Model = "Infusomat Space", SerialNumber = "BB-IP-2022-0234", Category = "Infusion Pump", PurchaseDate = new DateTime(2022,11,5), PurchasePrice = 3500m, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2027,11,5), DepartmentId = 2, Department = "Intensive Care Unit", Building = "Main", Floor = "2", Room = "ICU-203", AssignedTo = "Nurse Amina Salih", TechnicalSpecs = "0.1-999 ml/hr, occlusion alarm", PowerRequirements = "220V AC + Battery", RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.High, CreatedAt = now, IsActive = true },

                // ─── Laboratory ───
                new MedicalDevice { Id = 7, DeviceCode = "LAB-HA-007", DeviceName = "Mindray BC-6800 Hematology Analyzer", Manufacturer = "Mindray", Model = "BC-6800", SerialNumber = "MR-HA-2023-0678", Category = "Hematology Analyzer", PurchaseDate = new DateTime(2023,7,12), PurchasePrice = 65000m, SupplierId = 3, SupplierName = "Mindray Medical", WarrantyExpiryDate = new DateTime(2028,7,12), DepartmentId = 3, Department = "Central Laboratory", Building = "Annex", Floor = "1", Room = "LAB-101", AssignedTo = "Dr. Sara Ali", TechnicalSpecs = "CBC+DIFF, 120 samples/hr", PowerRequirements = "220V AC", RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.High, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 8, DeviceCode = "LAB-CA-008", DeviceName = "Roche Cobas c501 Chemistry Analyzer", Manufacturer = "Roche Diagnostics", Model = "Cobas c501", SerialNumber = "RD-CA-2022-0345", Category = "Chemistry Analyzer", PurchaseDate = new DateTime(2022,5,20), PurchasePrice = 95000m, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2027,5,20), DepartmentId = 3, Department = "Central Laboratory", Building = "Annex", Floor = "1", Room = "LAB-103", AssignedTo = "Tech. Nour El-Din", TechnicalSpecs = "800 tests/hr, ISE module", PowerRequirements = "220V AC", RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.UnderMaintenance, RiskClassification = RiskClass.High, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 9, DeviceCode = "LAB-CF-009", DeviceName = "Eppendorf 5430R Centrifuge", Manufacturer = "Eppendorf", Model = "5430R", SerialNumber = "EP-CF-2023-0123", Category = "Centrifuge", PurchaseDate = new DateTime(2023,2,28), PurchasePrice = 8500m, SupplierId = 7, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2026,2,28), DepartmentId = 3, Department = "Central Laboratory", Building = "Annex", Floor = "1", Room = "LAB-104", AssignedTo = "Tech. Yasmin Hassan", TechnicalSpecs = "30,000 × g, 15-7000 rpm, refrigerated", PowerRequirements = "220V AC", RequiresCalibration = false, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Medium, CreatedAt = now, IsActive = true },

                // ─── Emergency Room ───
                new MedicalDevice { Id = 10, DeviceCode = "ER-DF-010", DeviceName = "Philips HeartStart MRx", Manufacturer = "Philips Healthcare", Model = "HeartStart MRx", SerialNumber = "PH-DF-2023-0456", Category = "Defibrillator/Monitor", PurchaseDate = new DateTime(2023,6,1), PurchasePrice = 22000m, SupplierId = 4, SupplierName = "Philips Healthcare", WarrantyExpiryDate = new DateTime(2028,6,1), DepartmentId = 4, Department = "Emergency Room", Building = "Main", Floor = "Ground", Room = "ER-001", AssignedTo = "Dr. Khalid Omer", TechnicalSpecs = "Biphasic 1-360J, SpO2, ECG, NIBP", PowerRequirements = "Li-ion Battery + AC charger", RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Critical, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 11, DeviceCode = "ER-EC-011", DeviceName = "GE MAC 5500 ECG", Manufacturer = "GE Healthcare", Model = "MAC 5500", SerialNumber = "GE-EC-2022-0789", Category = "12-Lead ECG", PurchaseDate = new DateTime(2022,8,15), PurchasePrice = 5500m, SupplierId = 2, SupplierName = "GE Healthcare", WarrantyExpiryDate = new DateTime(2027,8,15), DepartmentId = 4, Department = "Emergency Room", Building = "Main", Floor = "Ground", Room = "ER-003", AssignedTo = "Nurse Rania Omer", TechnicalSpecs = "12-lead, resting ECG, interpretation", PowerRequirements = "100-240V AC + Battery", RequiresCalibration = false, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Medium, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 12, DeviceCode = "ER-OC-012", DeviceName = "Philips Respironics V60", Manufacturer = "Philips Healthcare", Model = "Respironics V60", SerialNumber = "PH-OC-2023-0234", Category = "Oxygen Concentrator", PurchaseDate = new DateTime(2023,3,10), PurchasePrice = 4200m, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2028,3,10), DepartmentId = 4, Department = "Emergency Room", Building = "Main", Floor = "Ground", Room = "ER-005", AssignedTo = "Tech. Hassan Ali", TechnicalSpecs = "5L/min, 93% O2, alarm system", PowerRequirements = "220V AC", RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.High, CreatedAt = now, IsActive = true },

                // ─── Operating Theatre ───
                new MedicalDevice { Id = 13, DeviceCode = "OR-AM-013", DeviceName = "Dräger Fabius GS Anesthesia", Manufacturer = "Dräger", Model = "Fabius GS", SerialNumber = "DR-AM-2023-0345", Category = "Anesthesia Machine", PurchaseDate = new DateTime(2023,5,20), PurchasePrice = 48000m, SupplierId = 5, SupplierName = "Dräger Medical", WarrantyExpiryDate = new DateTime(2028,5,20), DepartmentId = 5, Department = "Operating Theatre", Building = "Main", Floor = "3", Room = "OR-301", AssignedTo = "Dr. Mona Ibrahim", TechnicalSpecs = "Ventilation, Vapor 2000, O2/N2O/Air", PowerRequirements = "220V AC + Battery Backup", RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Critical, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 14, DeviceCode = "OR-ES-014", DeviceName = "Martin Electrosurgical Unit ES-400", Manufacturer = "Martin Medizintechnik", Model = "ME 400", SerialNumber = "MM-ES-2022-0567", Category = "Electrosurgical Unit", PurchaseDate = new DateTime(2022,10,8), PurchasePrice = 15000m, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2027,10,8), DepartmentId = 5, Department = "Operating Theatre", Building = "Main", Floor = "3", Room = "OR-302", AssignedTo = "Dr. Tariq Salih", TechnicalSpecs = "Cut/Coag 400W, bipolar/monopolar", PowerRequirements = "220V AC", RequiresCalibration = false, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.High, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 15, DeviceCode = "OR-OT-015", DeviceName = "Maquet Magnus OT Light", Manufacturer = "Getinge (Maquet)", Model = "Magnus LED", SerialNumber = "MQ-OT-2023-0123", Category = "OT Light", PurchaseDate = new DateTime(2023,1,25), PurchasePrice = 35000m, SupplierId = 1, SupplierName = "Siemens Healthineers", WarrantyExpiryDate = new DateTime(2028,1,25), DepartmentId = 5, Department = "Operating Theatre", Building = "Main", Floor = "3", Room = "OR-301", AssignedTo = "Dr. Mona Ibrahim", TechnicalSpecs = "160,000 lux, LED, shadowless", PowerRequirements = "220V AC", RequiresCalibration = false, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Medium, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 16, DeviceCode = "OR-OP-016", DeviceName = "Olympus VISERA Elite III Endoscope", Manufacturer = "Olympus", Model = "VISERA Elite III", SerialNumber = "OL-OP-2024-0234", Category = "Endoscope", PurchaseDate = new DateTime(2024,2,10), PurchasePrice = 75000m, SupplierId = 8, SupplierName = "Olympus Medical", WarrantyExpiryDate = new DateTime(2029,2,10), DepartmentId = 5, Department = "Operating Theatre", Building = "Main", Floor = "3", Room = "OR-303", AssignedTo = "Dr. Yasser Hamad", TechnicalSpecs = "Full HD, NBI, 3 chip CMOS", PowerRequirements = "100-240V AC", RequiresCalibration = false, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.High, CreatedAt = now, IsActive = true },

                // ─── CSSD (Sterilization) ───
                new MedicalDevice { Id = 17, DeviceCode = "CSSD-AC-017", DeviceName = "Getinge HS-66 Autoclave", Manufacturer = "Getinge", Model = "HS-66 Double Door", SerialNumber = "GT-AC-2021-0456", Category = "Autoclave", PurchaseDate = new DateTime(2021,7,15), PurchasePrice = 55000m, SupplierId = 1, SupplierName = "Siemens Healthineers", WarrantyExpiryDate = new DateTime(2026,7,15), DepartmentId = 6, Department = "Sterilization (CSSD)", Building = "Main", Floor = "1", Room = "CSSD-101", AssignedTo = "Tech. Huda Yousif", TechnicalSpecs = "660L, 134°C, vacuum drying", PowerRequirements = "380V 3-Phase, steam", RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Critical, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 18, DeviceCode = "CSSD-WD-018", DeviceName = "Miele PG 8583 Washer-Disinfector", Manufacturer = "Miele", Model = "PG 8583", SerialNumber = "ML-WD-2022-0789", Category = "Washer-Disinfector", PurchaseDate = new DateTime(2022,3,20), PurchasePrice = 28000m, SupplierId = 7, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2027,3,20), DepartmentId = 6, Department = "Sterilization (CSSD)", Building = "Main", Floor = "1", Room = "CSSD-102", AssignedTo = "Tech. Amira Hassan", TechnicalSpecs = "550L, thermodesinfection, drying", PowerRequirements = "380V 3-Phase, water supply", RequiresCalibration = false, RequiresPreventiveMaintenance = true, Status = DeviceStatus.UnderMaintenance, RiskClassification = RiskClass.High, CreatedAt = now, IsActive = true },

                // ─── Physiotherapy ───
                new MedicalDevice { Id = 19, DeviceCode = "PHY-US-019", DeviceName = "Chattanooga Intelect RPW", Manufacturer = "Chattanooga/DJO", Model = "Intech RPW Shockwave", SerialNumber = "CH-US-2023-0123", Category = "Shockwave Therapy", PurchaseDate = new DateTime(2023,8,5), PurchasePrice = 12000m, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2028,8,5), DepartmentId = 7, Department = "Physiotherapy", Building = "Annex", Floor = "2", Room = "PHY-201", AssignedTo = "Dr. Amira Eltayeb", TechnicalSpecs = "Radial pneumatic, 1-4 bar, 1-21 Hz", PowerRequirements = "220V AC + Battery", RequiresCalibration = false, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Medium, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 20, DeviceCode = "PHY-TS-020", DeviceName = "BTL-5000 Combo Ultrasound", Manufacturer = "BTL Industries", Model = "BTL-5000 5W", SerialNumber = "BT-TS-2023-0345", Category = "Therapeutic Ultrasound", PurchaseDate = new DateTime(2023,10,12), PurchasePrice = 6500m, SupplierId = 7, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2028,10,12), DepartmentId = 7, Department = "Physiotherapy", Building = "Annex", Floor = "2", Room = "PHY-202", AssignedTo = "Therapist Nour El-Din", TechnicalSpecs = "1/3 MHz, 0.1-3 W/cm²", PowerRequirements = "220V AC", RequiresCalibration = false, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Medium, CreatedAt = now, IsActive = true },

                // ─── Dialysis ───
                new MedicalDevice { Id = 21, DeviceCode = "DIA-HD-021", DeviceName = "Fresenius 5008 Hemodialysis", Manufacturer = "Fresenius Medical Care", Model = "5008s", SerialNumber = "FM-HD-2023-0567", Category = "Hemodialysis Machine", PurchaseDate = new DateTime(2023,4,20), PurchasePrice = 35000m, SupplierId = 6, SupplierName = "Fresenius Medical Care", WarrantyExpiryDate = new DateTime(2028,4,20), DepartmentId = 8, Department = "Dialysis Unit", Building = "Annex", Floor = "1", Room = "DIA-101", AssignedTo = "Dr. Yasser Hamad", TechnicalSpecs = "Online HDF, UF 0-4L/hr, blood flow 500ml/min", PowerRequirements = "220V AC, water supply", RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Critical, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 22, DeviceCode = "DIA-HD-022", DeviceName = "Fresenius 5008 Hemodialysis", Manufacturer = "Fresenius Medical Care", Model = "5008s", SerialNumber = "FM-HD-2023-0568", Category = "Hemodialysis Machine", PurchaseDate = new DateTime(2023,4,20), PurchasePrice = 35000m, SupplierId = 6, SupplierName = "Fresenius Medical Care", WarrantyExpiryDate = new DateTime(2028,4,20), DepartmentId = 8, Department = "Dialysis Unit", Building = "Annex", Floor = "1", Room = "DIA-102", AssignedTo = "Dr. Yasser Hamad", TechnicalSpecs = "Online HDF, UF 0-4L/hr, blood flow 500ml/min", PowerRequirements = "220V AC, water supply", RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Critical, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 23, DeviceCode = "DIA-HD-023", DeviceName = "Fresenius 5008 Hemodialysis", Manufacturer = "Fresenius Medical Care", Model = "5008s", SerialNumber = "FM-HD-2023-0569", Category = "Hemodialysis Machine", PurchaseDate = new DateTime(2023,4,20), PurchasePrice = 35000m, SupplierId = 6, SupplierName = "Fresenius Medical Care", WarrantyExpiryDate = new DateTime(2028,4,20), DepartmentId = 8, Department = "Dialysis Unit", Building = "Annex", Floor = "1", Room = "DIA-103", AssignedTo = "Nurse Salwa Ali", TechnicalSpecs = "Online HDF, UF 0-4L/hr, blood flow 500ml/min", PowerRequirements = "220V AC, water supply", RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Critical, CreatedAt = now, IsActive = true },

                // ─── Neonatal ICU (NICU) ───
                new MedicalDevice { Id = 24, DeviceCode = "NICU-IB-024", DeviceName = "Dräger Babyleo TN500 Incubator", Manufacturer = "Dräger", Model = "Babyleo TN500", SerialNumber = "DR-IB-2023-0123", Category = "Neonatal Incubator", PurchaseDate = new DateTime(2023,9,1), PurchasePrice = 55000m, SupplierId = 5, SupplierName = "Dräger Medical", WarrantyExpiryDate = new DateTime(2028,9,1), DepartmentId = 9, Department = "Neonatal ICU (NICU)", Building = "Main", Floor = "2", Room = "NICU-201", AssignedTo = "Dr. Nisreen Abdalla", TechnicalSpecs = "Servo control, humidity 10-95%, integrated scale", PowerRequirements = "220V AC + Battery Backup", RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Critical, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 25, DeviceCode = "NICU-PT-025", DeviceName = "Philips Infant Flow SiPAP", Manufacturer = "Philips Healthcare", Model = "Infant Flow SiPAP", SerialNumber = "PH-PT-2023-0345", Category = "Neonatal Ventilator", PurchaseDate = new DateTime(2023,6,15), PurchasePrice = 18000m, SupplierId = 4, SupplierName = "Philips Healthcare", WarrantyExpiryDate = new DateTime(2028,6,15), DepartmentId = 9, Department = "Neonatal ICU (NICU)", Building = "Main", Floor = "2", Room = "NICU-202", AssignedTo = "Nurse Rania Omer", TechnicalSpecs = "nCPAP/SiPAP, flow 0-15 L/min", PowerRequirements = "O2 + Air supply, 220V", RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Critical, CreatedAt = now, IsActive = true },

                // ─── Anesthesiology ───
                new MedicalDevice { Id = 26, DeviceCode = "ANES-PM-026", DeviceName = "GE Datex-Ohmeda S/5 Monitor", Manufacturer = "GE Healthcare", Model = "S/5 Light", SerialNumber = "GE-PM-2023-0456", Category = "Anesthesia Monitor", PurchaseDate = new DateTime(2023,3,10), PurchasePrice = 15000m, SupplierId = 2, SupplierName = "GE Healthcare", WarrantyExpiryDate = new DateTime(2028,3,10), DepartmentId = 10, Department = "Anesthesiology", Building = "Main", Floor = "3", Room = "OR-301", AssignedTo = "Dr. Tariq Salih", TechnicalSpecs = "ECG, SpO2, NIBP, EtCO2, MAC, AG", PowerRequirements = "100-240V AC + Battery", RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Critical, CreatedAt = now, IsActive = true },

                // ─── Outpatient Department ───
                new MedicalDevice { Id = 27, DeviceCode = "OPD-EC-027", DeviceName = "Mindray BeneHeart R12 ECG", Manufacturer = "Mindray", Model = "BeneHeart R12", SerialNumber = "MR-EC-2024-0234", Category = "12-Lead ECG", PurchaseDate = new DateTime(2024,1,15), PurchasePrice = 4800m, SupplierId = 3, SupplierName = "Mindray Medical", WarrantyExpiryDate = new DateTime(2029,1,15), DepartmentId = 11, Department = "Outpatient Department", Building = "Annex", Floor = "Ground", Room = "OPD-101", AssignedTo = "Dr. Rehab Osman", TechnicalSpecs = "12-lead, resting ECG, interpretation software", PowerRequirements = "100-240V AC + Battery", RequiresCalibration = false, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Medium, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 28, DeviceCode = "OPD-BP-028", DeviceName = "Welch Allyn Spot Vital Signs", Manufacturer = "Welch Allyn/Hill-Rom", Model = "Spot LXi", SerialNumber = "WA-BP-2023-0567", Category = "Vital Signs Monitor", PurchaseDate = new DateTime(2023,11,20), PurchasePrice = 3200m, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2028,11,20), DepartmentId = 11, Department = "Outpatient Department", Building = "Annex", Floor = "Ground", Room = "OPD-102", AssignedTo = "Nurse Amal Hassan", TechnicalSpecs = "NIBP, SpO2, Temp, HR", PowerRequirements = "220V AC + Battery", RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Low, CreatedAt = now, IsActive = true },

                // ─── Biomedical Engineering Workshop ───
                new MedicalDevice { Id = 29, DeviceCode = "BIO-ET-029", DeviceName = "Fluke Biomedical ESA615", Manufacturer = "Fluke Biomedical", Model = "ESA615", SerialNumber = "FL-ET-2023-0123", Category = "Electrical Safety Analyzer", PurchaseDate = new DateTime(2023,5,10), PurchasePrice = 18000m, SupplierId = 2, SupplierName = "GE Healthcare", WarrantyExpiryDate = new DateTime(2028,5,10), DepartmentId = 12, Department = "Biomedical Engineering", Building = "Basement", Floor = "B1", Room = "BIO-001", AssignedTo = "Eng. Mustafa Ahmed", TechnicalSpecs = "IEC 60601-1, leakage current, insulation", PowerRequirements = "220V AC", RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Medium, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 30, DeviceCode = "BIO-PS-030", DeviceName = "Fluke Impulse 7000D Patient Simulator", Manufacturer = "Fluke Biomedical", Model = "Impulse 7000D", SerialNumber = "FL-PS-2023-0345", Category = "Patient Simulator", PurchaseDate = new DateTime(2023,7,5), PurchasePrice = 22000m, SupplierId = 2, SupplierName = "GE Healthcare", WarrantyExpiryDate = new DateTime(2028,7,5), DepartmentId = 12, Department = "Biomedical Engineering", Building = "Basement", Floor = "B1", Room = "BIO-002", AssignedTo = "Eng. Mustafa Ahmed", TechnicalSpecs = "ECG, SpO2, NIBP, Temp, IBP, EtCO2, Pace", PowerRequirements = "220V AC + Battery", RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Medium, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 31, DeviceCode = "BIO-OP-031", DeviceName = "Rigel Uni-Thomp+ Ophthalmic Tester", Manufacturer = "Rigel Medical", Model = "Uni-Thomp+", SerialNumber = "RG-OP-2023-0456", Category = "Ophthalmic Tester", PurchaseDate = new DateTime(2023,9,20), PurchasePrice = 8500m, SupplierId = 7, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2028,9,20), DepartmentId = 12, Department = "Biomedical Engineering", Building = "Basement", Floor = "B1", Room = "BIO-001", AssignedTo = "Eng. Hassan Ali", TechnicalSpecs = "IEC 60601-2-6, slit lamp, indirect ophthalmoscope", PowerRequirements = "Battery", RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Low, CreatedAt = now, IsActive = true },

                // ═══════════════════════════════════════════
                // ─── Additional Laboratory Equipment ───
                // ═══════════════════════════════════════════
                new MedicalDevice { Id = 32, DeviceCode = "LAB-IM-032", DeviceName = "Sysmex XN-1000 Hematology Analyzer", Manufacturer = "Sysmex", Model = "XN-1000", SerialNumber = "SY-IM-2024-0101", Category = "Hematology Analyzer", PurchaseDate = new DateTime(2024,3,15), PurchasePrice = 52000m, SupplierId = 3, SupplierName = "Mindray Medical", WarrantyExpiryDate = new DateTime(2029,3,15), DepartmentId = 3, Department = "Central Laboratory", Building = "Annex", Floor = "1", Room = "LAB-102", AssignedTo = "Dr. Sara Ali", TechnicalSpecs = "CBC+DIFF+RET, 68 samples/hr, fluorescence flow cytometry", PowerRequirements = "100-240V AC, 50/60Hz, 350VA", RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.High, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 33, DeviceCode = "LAB-EL-033", DeviceName = "Roche Cobas e411 Immunoassay", Manufacturer = "Roche Diagnostics", Model = "Cobas e411", SerialNumber = "RD-EL-2023-0456", Category = "Immunoassay Analyzer", PurchaseDate = new DateTime(2023,8,10), PurchasePrice = 72000m, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2028,8,10), DepartmentId = 3, Department = "Central Laboratory", Building = "Annex", Floor = "1", Room = "LAB-105", AssignedTo = "Tech. Nour El-Din", TechnicalSpecs = "Electrochemiluminescence, 86 tests/hr, 17 parameters", PowerRequirements = "220V AC, 500VA", RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.High, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 34, DeviceCode = "LAB-CP-034", DeviceName = "Eppendorf Centrifuge 5424 R", Manufacturer = "Eppendorf", Model = "5424 R", SerialNumber = "EP-CP-2024-0234", Category = "Refrigerated Centrifuge", PurchaseDate = new DateTime(2024,1,20), PurchasePrice = 12500m, SupplierId = 7, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2029,1,20), DepartmentId = 3, Department = "Central Laboratory", Building = "Annex", Floor = "1", Room = "LAB-106", AssignedTo = "Tech. Yasmin Hassan", TechnicalSpecs = "Max 15,000 rpm, 4×100 mL rotor, 4°C-40°C", PowerRequirements = "220-240V AC, 50/60Hz, 630W", RequiresCalibration = false, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Medium, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 35, DeviceCode = "LAB-MB-035", DeviceName = "BD BACTEC FX40 Blood Culture", Manufacturer = "BD (Becton Dickinson)", Model = "BACTEC FX40", SerialNumber = "BD-MB-2023-0789", Category = "Blood Culture System", PurchaseDate = new DateTime(2023,10,5), PurchasePrice = 45000m, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2028,10,5), DepartmentId = 3, Department = "Central Laboratory", Building = "Annex", Floor = "1", Room = "LAB-107", AssignedTo = "Dr. Sara Ali", TechnicalSpecs = "Continuous monitoring, fluorescence detection, 120 bottle capacity", PowerRequirements = "220V AC, 50/60Hz, 300VA", RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.High, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 36, DeviceCode = "LAB-PT-036", DeviceName = "Stago STA-R Max Coagulation", Manufacturer = "Stago", Model = "STA-R Max", SerialNumber = "SG-PT-2024-0123", Category = "Coagulation Analyzer", PurchaseDate = new DateTime(2024,4,12), PurchasePrice = 38000m, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2029,4,12), DepartmentId = 3, Department = "Central Laboratory", Building = "Annex", Floor = "1", Room = "LAB-108", AssignedTo = "Tech. Nour El-Din", TechnicalSpecs = "PT, APTT, fibrinogen, D-dimer, 80 tests/hr", PowerRequirements = "100-240V AC, 50/60Hz, 400VA", RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.High, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 37, DeviceCode = "LAB-MS-037", DeviceName = "Bruker MALDI Biotyper", Manufacturer = "Bruker Daltonics", Model = "MBT Smart", SerialNumber = "BK-MS-2024-0345", Category = "Mass Spectrometer", PurchaseDate = new DateTime(2024,2,28), PurchasePrice = 185000m, SupplierId = 8, SupplierName = "Olympus Medical", WarrantyExpiryDate = new DateTime(2029,2,28), DepartmentId = 3, Department = "Central Laboratory", Building = "Annex", Floor = "1", Room = "LAB-109", AssignedTo = "Dr. Sara Ali", TechnicalSpecs = "Microbial ID by MALDI-TOF, 120 sec/sample", PowerRequirements = "220V AC, 3-phase, 3kVA", SoftwareVersion = "v4.1.10", NetworkConnected = true, RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.High, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 38, DeviceCode = "LAB-PC-038", DeviceName = "Thermo Fisher QuantStudio 3 PCR", Manufacturer = "Thermo Fisher Scientific", Model = "QuantStudio 3", SerialNumber = "TF-PC-2024-0456", Category = "Real-Time PCR", PurchaseDate = new DateTime(2024,5,10), PurchasePrice = 32000m, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2029,5,10), DepartmentId = 3, Department = "Central Laboratory", Building = "Annex", Floor = "1", Room = "LAB-110", AssignedTo = "Tech. Yasmin Hassan", TechnicalSpecs = "96-well, 5-color detection, 0.1-600 ng DNA input", PowerRequirements = "100-240V AC, 50/60Hz, 800W", SoftwareVersion = "v2.3", NetworkConnected = true, RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.High, CreatedAt = now, IsActive = true },

                // ═══════════════════════════════════════════
                // ─── Additional Radiology Equipment ───
                // ═══════════════════════════════════════════
                new MedicalDevice { Id = 39, DeviceCode = "RAD-MR-039", DeviceName = "Siemens MAGNETOM Aera 1.5T MRI", Manufacturer = "Siemens Healthineers", Model = "MAGNETOM Aera", SerialNumber = "SH-MR-2022-0789", Category = "MRI Scanner", PurchaseDate = new DateTime(2022,6,20), PurchasePrice = 1200000m, SupplierId = 1, SupplierName = "Siemens Healthineers", WarrantyExpiryDate = new DateTime(2027,6,20), DepartmentId = 1, Department = "Radiology", Building = "Main", Floor = "Ground", Room = "MRI-Suite", AssignedTo = "Dr. Ahmed Hassan", TechnicalSpecs = "1.5T, 48-channel, Tim4G, Dot engine, 200cm bore", PowerRequirements = "400V 3-Phase, 125A, cryogen-cooled", SoftwareVersion = "syngo MR E11", NetworkConnected = true, RequiresCalibration = true, RequiresPreventiveMaintenance = true, RequiresElectricalSafetyTesting = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Critical, SafetyNotes = "MRI Zone safety — ferromagnetic screening mandatory", CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 40, DeviceCode = "RAD-MG-040", DeviceName = "Hologic Selenia Dimensions Mammography", Manufacturer = "Hologic", Model = "Selenia Dimensions", SerialNumber = "HL-MG-2023-0234", Category = "Mammography", PurchaseDate = new DateTime(2023,9,15), PurchasePrice = 165000m, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2028,9,15), DepartmentId = 1, Department = "Radiology", Building = "Main", Floor = "1", Room = "MG-106", AssignedTo = "Tech. Layla Mustafa", TechnicalSpecs = "Digital breast tomosynthesis, 3D, 70μm pixel", PowerRequirements = "220V AC, 30A", RequiresCalibration = true, RequiresPreventiveMaintenance = true, RequiresElectricalSafetyTesting = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.High, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 41, DeviceCode = "RAD-FL-041", DeviceName = "Siemens Luminos Agile C-Arm", Manufacturer = "Siemens Healthineers", Model = "Luminos Agile", SerialNumber = "SH-FL-2023-0567", Category = "Fluoroscopy C-Arm", PurchaseDate = new DateTime(2023,11,8), PurchasePrice = 95000m, SupplierId = 1, SupplierName = "Siemens Healthineers", WarrantyExpiryDate = new DateTime(2028,11,8), DepartmentId = 1, Department = "Radiology", Building = "Main", Floor = "Ground", Room = "Cath-Lab", AssignedTo = "Dr. Ahmed Hassan", TechnicalSpecs = "Flat panel detector, 30×30cm, DSA, roadmapping", PowerRequirements = "380V 3-Phase, 50kVA", SoftwareVersion = "syngo XWP VA30", NetworkConnected = true, RequiresCalibration = true, RequiresPreventiveMaintenance = true, RequiresElectricalSafetyTesting = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.High, SafetyNotes = "Radiation area — dosimetry badges required", CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 42, DeviceCode = "RAD-BX-042", DeviceName = "Hologic Horizon DXA", Manufacturer = "Hologic", Model = "Horizon W", SerialNumber = "HL-BX-2024-0123", Category = "Bone Densitometer", PurchaseDate = new DateTime(2024,1,18), PurchasePrice = 78000m, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2029,1,18), DepartmentId = 1, Department = "Radiology", Building = "Main", Floor = "1", Room = "DXA-107", AssignedTo = "Tech. Mohamed Abdallah", TechnicalSpecs = "Fan-beam, dual-energy, whole body & spine BMD", PowerRequirements = "100-240V AC, 50/60Hz, 400VA", NetworkConnected = true, RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Medium, CreatedAt = now, IsActive = true },

                // ═══════════════════════════════════════════
                // ─── Additional Radiology Equipment (Batch 2) ───
                // ═══════════════════════════════════════════
                new MedicalDevice { Id = 43, DeviceCode = "RAD-PCT-043", DeviceName = "Siemens Biograph Vision PET-CT", Manufacturer = "Siemens Healthineers", Model = "Biograph Vision 600", SerialNumber = "SH-PCT-2023-0890", Category = "PET-CT Scanner", PurchaseDate = new DateTime(2023,5,12), PurchasePrice = 2500000m, SupplierId = 1, SupplierName = "Siemens Healthineers", WarrantyExpiryDate = new DateTime(2028,5,12), DepartmentId = 1, Department = "Radiology", Building = "Main", Floor = "Ground", Room = "PET-CT-Suite", AssignedTo = "Dr. Ahmed Hassan", TechnicalSpecs = "64-slice CT, 4-ring PET, 78cm bore, HD·PET with TrueV, 70cm field-of-view", PowerRequirements = "400V 3-Phase, 150A, chilled water cooling", SoftwareVersion = "syngo.via VB60", NetworkConnected = true, RequiresCalibration = true, RequiresPreventiveMaintenance = true, RequiresElectricalSafetyTesting = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Critical, SafetyNotes = "Radioactive tracer handling — radiation safety officer required", CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 44, DeviceCode = "RAD-PX-044", DeviceName = "Canon CXDI-810C Portable X-Ray", Manufacturer = "Canon Medical Systems", Model = "CXDI-810C", SerialNumber = "CM-PX-2024-0345", Category = "Portable X-Ray", PurchaseDate = new DateTime(2024,3,8), PurchasePrice = 45000m, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2029,3,8), DepartmentId = 1, Department = "Radiology", Building = "Main", Floor = "1", Room = "RAD-Store-108", AssignedTo = "Tech. Mohamed Abdallah", TechnicalSpecs = " wireless flat panel 17×17, 143μm pixel, 16-bit grayscale", PowerRequirements = "Rechargeable Li-ion battery, 220V charger", SoftwareVersion = "v3.2.0", NetworkConnected = true, RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.High, SafetyNotes = "Mobile radiation source — 2m exclusion zone during exposure", CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 45, DeviceCode = "RAD-US-045", DeviceName = "GE LOGIQ E10 Premium Ultrasound", Manufacturer = "GE Healthcare", Model = "LOGIQ E10", SerialNumber = "GE-US-2024-0567", Category = "Premium Ultrasound", PurchaseDate = new DateTime(2024,6,20), PurchasePrice = 195000m, SupplierId = 2, SupplierName = "GE Healthcare", WarrantyExpiryDate = new DateTime(2029,6,20), DepartmentId = 1, Department = "Radiology", Building = "Main", Floor = "1", Room = "US-109", AssignedTo = "Dr. Layla Mustafa", TechnicalSpecs = "cSound architecture, 4D volume imaging, CrystalPure transducers, elastography", PowerRequirements = "100-240V AC, 50/60Hz, 1kVA", SoftwareVersion = "R7", NetworkConnected = true, RequiresCalibration = false, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Medium, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 46, DeviceCode = "RAD-DF-046", DeviceName = "Philips Azurion 7 B20 Angiography", Manufacturer = "Philips Healthcare", Model = "Azurion 7 B20", SerialNumber = "PH-DF-2023-0678", Category = "Digital Subtraction Angiography", PurchaseDate = new DateTime(2023,10,15), PurchasePrice = 850000m, SupplierId = 4, SupplierName = "Philips Healthcare", WarrantyExpiryDate = new DateTime(2028,10,15), DepartmentId = 1, Department = "Radiology", Building = "Main", Floor = "Ground", Room = "Cath-Lab-2", AssignedTo = "Dr. Ahmed Hassan", TechnicalSpecs = "20-flat panel detector, 4K imaging, 3D roadmap, ClarityIQ technology", PowerRequirements = "400V 3-Phase, 100kVA", SoftwareVersion = "Azurion R3.1", NetworkConnected = true, RequiresCalibration = true, RequiresPreventiveMaintenance = true, RequiresElectricalSafetyTesting = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Critical, SafetyNotes = "High-dose radiation — lead aprons + thyroid shields mandatory", CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 47, DeviceCode = "RAD-OC-047", DeviceName = "Canon Aquilion Lightning CT", Manufacturer = "Canon Medical Systems", Model = "Aquilion Lightning 80", SerialNumber = "CM-OC-2024-0789", Category = "CT Scanner", PurchaseDate = new DateTime(2024,2,28), PurchasePrice = 680000m, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2029,2,28), DepartmentId = 1, Department = "Radiology", Building = "Main", Floor = "Ground", Room = "CT-Suite-2", AssignedTo = "Dr. Ahmed Hassan", TechnicalSpecs = "80-slice, 0.5mm slice thickness, 350° gantry, AiCE deep learning reconstruction", PowerRequirements = "400V 3-Phase, 120A", SoftwareVersion = "CT Platform V6.2", NetworkConnected = true, RequiresCalibration = true, RequiresPreventiveMaintenance = true, RequiresElectricalSafetyTesting = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.High, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 48, DeviceCode = "RAD-OG-048", DeviceName = "GE Senographe Pristina Digital Mammography", Manufacturer = "GE Healthcare", Model = "Seno Pristina", SerialNumber = "GE-OG-2024-0234", Category = "Digital Mammography", PurchaseDate = new DateTime(2024,4,10), PurchasePrice = 145000m, SupplierId = 2, SupplierName = "GE Healthcare", WarrantyExpiryDate = new DateTime(2029,4,10), DepartmentId = 1, Department = "Radiology", Building = "Main", Floor = "1", Room = "MG-110", AssignedTo = "Tech. Layla Mustafa", TechnicalSpecs = "Full-field digital, tomosynthesis, 70μm pixel, 24×30cm detector", PowerRequirements = "220V AC, 50/60Hz, 5kVA", SoftwareVersion = "AW Server 3.2", NetworkConnected = true, RequiresCalibration = true, RequiresPreventiveMaintenance = true, RequiresElectricalSafetyTesting = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.High, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 49, DeviceCode = "RAD-FL-049", DeviceName = "Ziehm Vision RFD 3D C-Arm", Manufacturer = "Ziehm Imaging", Model = "Vision RFD 3D", SerialNumber = "ZI-FL-2024-0456", Category = "Mobile C-Arm", PurchaseDate = new DateTime(2024,1,5), PurchasePrice = 125000m, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2029,1,5), DepartmentId = 1, Department = "Radiology", Building = "Main", Floor = "Ground", Room = "RAD-Mobile", AssignedTo = "Tech. Mohamed Abdallah", TechnicalSpecs = "Flat panel detector, 3D imaging, 30×30cm FOV, 15kW generator", PowerRequirements = "220V AC + Battery, mobile unit", SoftwareVersion = "Ziehm View 3.1", NetworkConnected = true, RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.High, SafetyNotes = "Mobile radiation — dosimetry badges + portable barriers required", CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 50, DeviceCode = "RAD-DC-050", DeviceName = "AGFA CR 30-X Digitizer", Manufacturer = "AGFA HealthCare", Model = "CR 30-X", SerialNumber = "AG-DC-2023-0567", Category = "Computed Radiography", PurchaseDate = new DateTime(2023,8,22), PurchasePrice = 32000m, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2028,8,22), DepartmentId = 1, Department = "Radiology", Building = "Main", Floor = "1", Room = "CR-111", AssignedTo = "Tech. Mohamed Abdallah", TechnicalSpecs = "IP reader, 17×17 & 14×17 cassettes, 100μm resolution, 5 sec readout", PowerRequirements = "220V AC, 50/60Hz, 600VA", NetworkConnected = true, RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Medium, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 51, DeviceCode = "RAD-WS-051", DeviceName = "Barco MDNC-8161 Diagnostic Monitor", Manufacturer = "Barco", Model = "MDNC-8161 Coronis 6MP", SerialNumber = "BC-WS-2024-0123", Category = "Diagnostic Workstation", PurchaseDate = new DateTime(2024,5,15), PurchasePrice = 18000m, SupplierId = 7, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2029,5,15), DepartmentId = 1, Department = "Radiology", Building = "Main", Floor = "1", Room = "Read-112", AssignedTo = "Dr. Ahmed Hassan", TechnicalSpecs = "Dual 30MP, 6MP grayscale, DICOM Part 14 calibrated, 1200 nit brightness", PowerRequirements = "100-240V AC, 50/60Hz, 200W", SoftwareVersion = "Coronis Uniti v1.0", NetworkConnected = true, RequiresCalibration = true, RequiresPreventiveMaintenance = false, Status = DeviceStatus.Active, RiskClassification = RiskClass.Medium, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 52, DeviceCode = "RAD-CD-052", DeviceName = "Radformation ClearCheck Dose Monitoring", Manufacturer = "Radformation", Model = "ClearCheck Suite", SerialNumber = "RF-CD-2024-0345", Category = "Radiation Dose Monitoring", PurchaseDate = new DateTime(2024,7,1), PurchasePrice = 25000m, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2029,7,1), DepartmentId = 1, Department = "Radiology", Building = "Main", Floor = "1", Room = "RAD-Office", AssignedTo = "Dr. Ahmed Hassan", TechnicalSpecs = "Automated dose tracking, DICOM RDSR, ACR DIR registry integration", PowerRequirements = "Cloud-based SaaS, 220V UPS for local gateway", SoftwareVersion = "v2024.1", NetworkConnected = true, RequiresCalibration = false, RequiresPreventiveMaintenance = false, Status = DeviceStatus.Active, RiskClassification = RiskClass.Low, CreatedAt = now, IsActive = true },

                // ═══════════════════════════════════════════
                // ─── Additional Laboratory Equipment (Batch 2) ───
                // ═══════════════════════════════════════════
                new MedicalDevice { Id = 53, DeviceCode = "LAB-BA-053", DeviceName = "Beckman Coulter DxH 900 Hematology", Manufacturer = "Beckman Coulter", Model = "DxH 900", SerialNumber = "BC-BA-2024-0567", Category = "Hematology Analyzer", PurchaseDate = new DateTime(2024,8,15), PurchasePrice = 78000m, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2029,8,15), DepartmentId = 3, Department = "Central Laboratory", Building = "Annex", Floor = "1", Room = "LAB-111", AssignedTo = "Dr. Sara Ali", TechnicalSpecs = "CBC+DIFF+NRBC, 125 samples/hr, VCSn technology, automated slide maker", PowerRequirements = "100-240V AC, 50/60Hz, 500VA", SoftwareVersion = "v3.1.0", NetworkConnected = true, RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.High, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 54, DeviceCode = "LAB-CS-054", DeviceName = "Abbott ARCHITECT c8000 Chemistry", Manufacturer = "Abbott Diagnostics", Model = "ARCHITECT c8000", SerialNumber = "AB-CS-2023-0890", Category = "Chemistry Analyzer", PurchaseDate = new DateTime(2023,11,20), PurchasePrice = 145000m, SupplierId = 7, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2028,11,20), DepartmentId = 3, Department = "Central Laboratory", Building = "Annex", Floor = "1", Room = "LAB-112", AssignedTo = "Tech. Nour El-Din", TechnicalSpecs = "800 tests/hr photometric, 240 ISE tests/hr, 110 reagent positions", PowerRequirements = "220V AC, 50/60Hz, 1.2kVA", SoftwareVersion = "v6.2", NetworkConnected = true, RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.High, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 55, DeviceCode = "LAB-UR-055", DeviceName = "Sysmex UF-5000 Urine Analyzer", Manufacturer = "Sysmex", Model = "UF-5000", SerialNumber = "SY-UR-2024-0123", Category = "Urine Analyzer", PurchaseDate = new DateTime(2024,2,10), PurchasePrice = 42000m, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2029,2,10), DepartmentId = 3, Department = "Central Laboratory", Building = "Annex", Floor = "1", Room = "LAB-113", AssignedTo = "Tech. Yasmin Hassan", TechnicalSpecs = "Flow cytometry, 90 samples/hr, RBC/WBC/EC/BACT quantification", PowerRequirements = "100-240V AC, 50/60Hz, 300VA", SoftwareVersion = "v2.0.1", NetworkConnected = true, RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Medium, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 56, DeviceCode = "LAB-GC-056", DeviceName = "Eppendorf Mastercycler X50 PCR", Manufacturer = "Eppendorf", Model = "Mastercycler X50 gradient", SerialNumber = "EP-GC-2024-0345", Category = "Thermal Cycler", PurchaseDate = new DateTime(2024,6,5), PurchasePrice = 18500m, SupplierId = 7, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2029,6,5), DepartmentId = 3, Department = "Central Laboratory", Building = "Annex", Floor = "1", Room = "LAB-114", AssignedTo = "Tech. Yasmin Hassan", TechnicalSpecs = "Gradient PCR, 96-well, 0.2-100 μL tubes, ramp rate 5°C/sec", PowerRequirements = "100-240V AC, 50/60Hz, 900W", SoftwareVersion = "v2.5", NetworkConnected = false, RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Medium, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 57, DeviceCode = "LAB-EL-057", DeviceName = "Bio-Rad D-10 HPLC Hemoglobin", Manufacturer = "Bio-Rad Laboratories", Model = "D-10", SerialNumber = "BR-EL-2023-0678", Category = "HPLC Analyzer", PurchaseDate = new DateTime(2023,9,12), PurchasePrice = 35000m, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2028,9,12), DepartmentId = 3, Department = "Central Laboratory", Building = "Annex", Floor = "1", Room = "LAB-115", AssignedTo = "Dr. Sara Ali", TechnicalSpecs = "HbA1c, HbF, HbA2 quantification, 2 min/sample, ion-exchange HPLC", PowerRequirements = "100-240V AC, 50/60Hz, 150VA", NetworkConnected = true, RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.High, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 58, DeviceCode = "LAB-WS-058", DeviceName = "Siemens Aptio Automation Track", Manufacturer = "Siemens Healthineers", Model = "Aptio Automation", SerialNumber = "SH-WS-2024-0789", Category = "Laboratory Automation", PurchaseDate = new DateTime(2024,1,8), PurchasePrice = 850000m, SupplierId = 1, SupplierName = "Siemens Healthineers", WarrantyExpiryDate = new DateTime(2029,1,8), DepartmentId = 3, Department = "Central Laboratory", Building = "Annex", Floor = "1", Room = "LAB-Main", AssignedTo = "Dr. Sara Ali", TechnicalSpecs = "Pre-analytic, analytic, post-analytic automation, 300 tubes/hr throughput", PowerRequirements = "220V AC, 3-phase, 5kVA", SoftwareVersion = "Atellica Data Manager v4.0", NetworkConnected = true, RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.High, SafetyNotes = "Moving parts — keep clear during operation", CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 59, DeviceCode = "LAB-SG-059", DeviceName = "Sartorius BP-221S Balance", Manufacturer = "Sartorius", Model = "BP 221S", SerialNumber = "SA-SG-2024-0234", Category = "Analytical Balance", PurchaseDate = new DateTime(2024,3,20), PurchasePrice = 4500m, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2029,3,20), DepartmentId = 3, Department = "Central Laboratory", Building = "Annex", Floor = "1", Room = "LAB-116", AssignedTo = "Tech. Nour El-Din", TechnicalSpecs = "220g capacity, 0.1mg readability, internal calibration, draft shield", PowerRequirements = "220V AC, 50/60Hz, 15W", NetworkConnected = false, RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Medium, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 60, DeviceCode = "LAB-PH-060", DeviceName = "Mettler Toledo SevenExcellence pH Meter", Manufacturer = "Mettler Toledo", Model = "SevenExcellence S475", SerialNumber = "MT-PH-2024-0456", Category = "pH/Ion Meter", PurchaseDate = new DateTime(2024,4,18), PurchasePrice = 6200m, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2029,4,18), DepartmentId = 3, Department = "Central Laboratory", Building = "Annex", Floor = "1", Room = "LAB-116", AssignedTo = "Tech. Yasmin Hassan", TechnicalSpecs = "pH range -2.000 to 20.000, ±0.002 accuracy, mV, ISE, conductivity", PowerRequirements = "100-240V AC, 50/60Hz, 30W", NetworkConnected = false, RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Low, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 61, DeviceCode = "LAB-WB-061", DeviceName = "Thermo Fisher Heratherm IGS180 Incubator", Manufacturer = "Thermo Fisher Scientific", Model = "Heratherm IGS180", SerialNumber = "TF-WB-2023-0567", Category = "Microbiology Incubator", PurchaseDate = new DateTime(2023,7,25), PurchasePrice = 8500m, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2028,7,25), DepartmentId = 3, Department = "Central Laboratory", Building = "Annex", Floor = "1", Room = "LAB-117", AssignedTo = "Tech. Nour El-Din", TechnicalSpecs = "176L capacity, 5-75°C, IR sensor, gravity convection", PowerRequirements = "220V AC, 50/60Hz, 550W", NetworkConnected = false, RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Medium, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 62, DeviceCode = "LAB-BR-062", DeviceName = "Thermo Fisher Cryotome FSE Cryostat", Manufacturer = "Thermo Fisher Scientific", Model = "Cryotome FSE", SerialNumber = "TF-BR-2024-0678", Category = "Cryostat Microtome", PurchaseDate = new DateTime(2024,5,22), PurchasePrice = 28000m, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2029,5,22), DepartmentId = 3, Department = "Central Laboratory", Building = "Annex", Floor = "1", Room = "LAB-118", AssignedTo = "Dr. Sara Ali", TechnicalSpecs = "Section thickness 0.5-100μm, -35°C chamber, rapid freezing", PowerRequirements = "220V AC, 50/60Hz, 420W", NetworkConnected = false, RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.High, SafetyNotes = "Biohazard risk — UV decontamination cycle required", CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 63, DeviceCode = "LAB-FW-063", DeviceName = "Bio-Rad ChemiDoc MP Imaging", Manufacturer = "Bio-Rad Laboratories", Model = "ChemiDoc MP", SerialNumber = "BR-FW-2024-0789", Category = "Western Blot Imager", PurchaseDate = new DateTime(2024,9,10), PurchasePrice = 52000m, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2029,9,10), DepartmentId = 3, Department = "Central Laboratory", Building = "Annex", Floor = "1", Room = "LAB-119", AssignedTo = "Tech. Yasmin Hassan", TechnicalSpecs = "Fluorescence, chemiluminescence, colorimetric, 16-bit CCD camera", PowerRequirements = "100-240V AC, 50/60Hz, 400VA", SoftwareVersion = "Image Lab Touch v3.0", NetworkConnected = true, RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Medium, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 64, DeviceCode = "LAB-LR-064", DeviceName = "Eppendorf BioPhotometer D30 UV/Vis", Manufacturer = "Eppendorf", Model = "BioPhotometer D30", SerialNumber = "EP-LR-2024-0890", Category = "Spectrophotometer", PurchaseDate = new DateTime(2024,7,8), PurchasePrice = 9800m, SupplierId = 7, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2029,7,8), DepartmentId = 3, Department = "Central Laboratory", Building = "Annex", Floor = "1", Room = "LAB-120", AssignedTo = "Tech. Nour El-Din", TechnicalSpecs = "190-1100nm range, 1nm bandwidth, 0.001-4.000 Abs, kinetics", PowerRequirements = "100-240V AC, 50/60Hz, 60W", NetworkConnected = true, RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Medium, CreatedAt = now, IsActive = true },

                // ═══════════════════════════════════════════
                // ─── Additional Radiology Equipment (Batch 3) ───
                // ═══════════════════════════════════════════
                new MedicalDevice { Id = 65, DeviceCode = "RAD-MR-065", DeviceName = "GE SIGNA Pioneer 3.0T MRI", Manufacturer = "GE Healthcare", Model = "SIGNA Pioneer", SerialNumber = "GE-MR-2024-0890", Category = "MRI Scanner", PurchaseDate = new DateTime(2024,3,15), PurchasePrice = 1800000m, SupplierId = 2, SupplierName = "GE Healthcare", WarrantyExpiryDate = new DateTime(2029,3,15), DepartmentId = 1, Department = "Radiology", Building = "Main", Floor = "Ground", Room = "MRI-Suite-2", AssignedTo = "Dr. Ahmed Hassan", TechnicalSpecs = "3.0T, 70cm wide bore, 400 gradients, AIR Recon DL, Silent Scan", PowerRequirements = "400V 3-Phase, 180A, liquid helium-cooled", SoftwareVersion = "27.0", NetworkConnected = true, RequiresCalibration = true, RequiresPreventiveMaintenance = true, RequiresElectricalSafetyTesting = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Critical, SafetyNotes = "3T field — strict ferromagnetic screening, implant safety protocols", CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 66, DeviceCode = "RAD-CT-066", DeviceName = "Siemens SOMATOM Force Dual-Source CT", Manufacturer = "Siemens Healthineers", Model = "SOMATOM Force", SerialNumber = "SH-CT-2024-0901", Category = "CT Scanner", PurchaseDate = new DateTime(2024,5,20), PurchasePrice = 1500000m, SupplierId = 1, SupplierName = "Siemens Healthineers", WarrantyExpiryDate = new DateTime(2029,5,20), DepartmentId = 1, Department = "Radiology", Building = "Main", Floor = "Ground", Room = "CT-Suite-3", AssignedTo = "Dr. Ahmed Hassan", TechnicalSpecs = "Dual-source, 2×128 slices, 710ms rotation, 500mm FOV, Tin filter", PowerRequirements = "400V 3-Phase, 150A", SoftwareVersion = "syngo CT VB30", NetworkConnected = true, RequiresCalibration = true, RequiresPreventiveMaintenance = true, RequiresElectricalSafetyTesting = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Critical, SafetyNotes = "High-dose radiation — automated dose monitoring required", CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 67, DeviceCode = "RAD-XR-067", DeviceName = "Canon RADspeed Pro Shima DR", Manufacturer = "Canon Medical Systems", Model = "RADspeed Pro Shima", SerialNumber = "CM-XR-2024-0912", Category = "Digital X-Ray", PurchaseDate = new DateTime(2024,7,10), PurchasePrice = 185000m, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2029,7,10), DepartmentId = 1, Department = "Radiology", Building = "Main", Floor = "1", Room = "XR-113", AssignedTo = "Tech. Mohamed Abdallah", TechnicalSpecs = "Ceiling-mounted, 800mA, 150kV, wireless detector 17×17, auto tracking", PowerRequirements = "380V 3-Phase, 60kVA", SoftwareVersion = "Console 3D v4.0", NetworkConnected = true, RequiresCalibration = true, RequiresPreventiveMaintenance = true, RequiresElectricalSafetyTesting = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.High, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 68, DeviceCode = "RAD-US-068", DeviceName = "Samsung RS85A Prestige Ultrasound", Manufacturer = "Samsung Medison", Model = "RS85A Prestige", SerialNumber = "SM-US-2024-0923", Category = "Premium Ultrasound", PurchaseDate = new DateTime(2024,6,15), PurchasePrice = 165000m, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2029,6,15), DepartmentId = 1, Department = "Radiology", Building = "Main", Floor = "1", Room = "US-114", AssignedTo = "Dr. Layla Mustafa", TechnicalSpecs = "3D/4D imaging, S-Vue transducers, elasticity imaging, CrystalScope", PowerRequirements = "100-240V AC, 50/60Hz, 900VA", SoftwareVersion = "V2.3", NetworkConnected = true, RequiresCalibration = false, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Medium, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 69, DeviceCode = "RAD-DF-069", DeviceName = "Canon Infinix-i 4K Angiography", Manufacturer = "Canon Medical Systems", Model = "Infinix-i 4K", SerialNumber = "CM-DF-2024-0934", Category = "Digital Subtraction Angiography", PurchaseDate = new DateTime(2024,4,5), PurchasePrice = 920000m, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2029,4,5), DepartmentId = 1, Department = "Radiology", Building = "Main", Floor = "Ground", Room = "Cath-Lab-3", AssignedTo = "Dr. Ahmed Hassan", TechnicalSpecs = "4K flat panel 30×30cm, 3D roadmapping, DSA, DynaCT, stroke navigation", PowerRequirements = "400V 3-Phase, 110kVA", SoftwareVersion = "VITREA Angio Suite v2.0", NetworkConnected = true, RequiresCalibration = true, RequiresPreventiveMaintenance = true, RequiresElectricalSafetyTesting = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Critical, SafetyNotes = "High-dose interventional — dosimetry badges + eye protection mandatory", CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 70, DeviceCode = "RAD-NM-070", DeviceName = "GE Discovery NM/CT 670 Pro SPECT-CT", Manufacturer = "GE Healthcare", Model = "Discovery NM/CT 670 Pro", SerialNumber = "GE-NM-2024-0945", Category = "SPECT-CT Scanner", PurchaseDate = new DateTime(2024,8,12), PurchasePrice = 980000m, SupplierId = 2, SupplierName = "GE Healthcare", WarrantyExpiryDate = new DateTime(2029,8,12), DepartmentId = 1, Department = "Radiology", Building = "Main", Floor = "Ground", Room = "NM-Suite", AssignedTo = "Dr. Ahmed Hassan", TechnicalSpecs = "SPECT+CT, CZT detectors, 16-slice CT, cardiac & whole-body imaging", PowerRequirements = "400V 3-Phase, 100A", SoftwareVersion = "Xeleris 4.0", NetworkConnected = true, RequiresCalibration = true, RequiresPreventiveMaintenance = true, RequiresElectricalSafetyTesting = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Critical, SafetyNotes = "Radiopharmaceutical handling — radiation safety protocols required", CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 71, DeviceCode = "RAD-VR-071", DeviceName = "GE XR240am-d Digital X-Ray", Manufacturer = "GE Healthcare", Model = "XR240am-d", SerialNumber = "GE-VR-2024-0956", Category = "Digital X-Ray (Floor-mounted)", PurchaseDate = new DateTime(2024,9,1), PurchasePrice = 145000m, SupplierId = 2, SupplierName = "GE Healthcare", WarrantyExpiryDate = new DateTime(2029,9,1), DepartmentId = 1, Department = "Radiology", Building = "Main", Floor = "1", Room = "XR-115", AssignedTo = "Tech. Mohamed Abdallah", TechnicalSpecs = "500mA, 150kV, motorized 4-way floating table, wireless detector", PowerRequirements = "380V 3-Phase, 50kVA", NetworkConnected = true, RequiresCalibration = true, RequiresPreventiveMaintenance = true, RequiresElectricalSafetyTesting = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.High, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 72, DeviceCode = "RAD-MG-072", DeviceName = "Fujifilm Amulet Innovality Mammography", Manufacturer = "Fujifilm Healthcare", Model = "Amulet Innovality", SerialNumber = "FF-MG-2024-0967", Category = "Digital Mammography", PurchaseDate = new DateTime(2024,2,18), PurchasePrice = 175000m, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2029,2,18), DepartmentId = 1, Department = "Radiology", Building = "Main", Floor = "1", Room = "MG-116", AssignedTo = "Tech. Layla Mustafa", TechnicalSpecs = "Full-field digital, tomosynthesis, 75μm pixel, selenium detector, compression control", PowerRequirements = "220V AC, 50/60Hz, 6kVA", SoftwareVersion = "FAIR-EX v3.0", NetworkConnected = true, RequiresCalibration = true, RequiresPreventiveMaintenance = true, RequiresElectricalSafetyTesting = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.High, CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 73, DeviceCode = "RAD-FL-073", DeviceName = "Siemens Artis pheno Robotic Angio", Manufacturer = "Siemens Healthineers", Model = "Artis pheno", SerialNumber = "SH-FL-2024-0978", Category = "Robotic Angiography", PurchaseDate = new DateTime(2024,10,1), PurchasePrice = 1350000m, SupplierId = 1, SupplierName = "Siemens Healthineers", WarrantyExpiryDate = new DateTime(2029,10,1), DepartmentId = 1, Department = "Radiology", Building = "Main", Floor = "Ground", Room = "Hybrid-OR", AssignedTo = "Dr. Ahmed Hassan", TechnicalSpecs = "Robot-mounted C-arm, 30×40cm detector, 3D/4D imaging, needle vision, auto positioning", PowerRequirements = "400V 3-Phase, 80kVA", SoftwareVersion = "syngo Xray Workplace VA30", NetworkConnected = true, RequiresCalibration = true, RequiresPreventiveMaintenance = true, RequiresElectricalSafetyTesting = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Critical, SafetyNotes = "Robotic system — keep clear of moving parts during autonomous mode", CreatedAt = now, IsActive = true },
                new MedicalDevice { Id = 74, DeviceCode = "RAD-QC-074", DeviceName = "IBA Dose Verification System", Manufacturer = "IBA Dosimetry", Model = "VeriSoft 7.3", SerialNumber = "IB-QC-2024-0989", Category = "Quality Control System", PurchaseDate = new DateTime(2024,11,5), PurchasePrice = 42000m, SupplierName = "MedTech Sudan", WarrantyExpiryDate = new DateTime(2029,11,5), DepartmentId = 1, Department = "Radiology", Building = "Main", Floor = "1", Room = "RAD-QC", AssignedTo = "Dr. Ahmed Hassan", TechnicalSpecs = "EPID dosimetry, planar & 3D dose verification, gamma analysis", PowerRequirements = "220V AC, 50/60Hz, 200W", SoftwareVersion = "VeriSoft 7.3", NetworkConnected = true, RequiresCalibration = true, RequiresPreventiveMaintenance = true, Status = DeviceStatus.Active, RiskClassification = RiskClass.Medium, CreatedAt = now, IsActive = true },
            });
            await ctx.SaveChangesAsync();

            // ═══════════════════════════════════════════
            // 5. MAINTENANCE RECORDS (8 records)
            // ═══════════════════════════════════════════
            ctx.MaintenanceRecords.AddRange(new[]
            {
                new MaintenanceRecord { Id = 1, DeviceId = 1, Type = MaintenanceType.Preventive, Title = "Quarterly PM — Siemens Multix DR", ScheduledDate = now.AddDays(7), NextDueDate = now.AddDays(97), Recurrence = RecurrenceFrequency.Quarterly, RecurrenceInterval = 3, PerformedBy = "Biomedical Team", Status = MaintenanceStatus.Scheduled, LaborCost = 500m, CreatedAt = now, IsActive = true },
                new MaintenanceRecord { Id = 2, DeviceId = 2, Type = MaintenanceType.Preventive, Title = "Annual PM — GE CT Scanner", ScheduledDate = now.AddDays(-10), CompletedDate = now.AddDays(-8), NextDueDate = now.AddDays(355), Recurrence = RecurrenceFrequency.Annually, PerformedBy = "Siemens Engineer", Status = MaintenanceStatus.Completed, Findings = "Tube wear within limits, fan filter replaced", ActionsTaken = "Cleaned detector array, replaced filters, recalibrated", LaborCost = 2000m, PartsCost = 800m, CreatedAt = now, IsActive = true },
                new MaintenanceRecord { Id = 3, DeviceId = 4, Type = MaintenanceType.Preventive, Title = "Monthly PM — Dräger Ventilator", ScheduledDate = now.AddDays(5), NextDueDate = now.AddDays(35), Recurrence = RecurrenceFrequency.Monthly, PerformedBy = "Biomedical Team", Status = MaintenanceStatus.Scheduled, LaborCost = 300m, CreatedAt = now, IsActive = true },
                new MaintenanceRecord { Id = 4, DeviceId = 6, Type = MaintenanceType.Corrective, Title = "Emergency Repair — Infusion Pump Motor", ScheduledDate = now.AddDays(-5), CompletedDate = now.AddDays(-4), PerformedBy = "Eng. Mustafa", Status = MaintenanceStatus.Completed, Findings = "Stepper motor failure", ActionsTaken = "Replaced motor, recalibrated flow rate", LaborCost = 200m, PartsCost = 450m, CreatedAt = now, IsActive = true },
                new MaintenanceRecord { Id = 5, DeviceId = 8, Type = MaintenanceType.Corrective, Title = "Repair — Chemistry Analyzer Probe", ScheduledDate = now.AddDays(-2), PerformedBy = "Roche Engineer", Status = MaintenanceStatus.InProgress, Findings = "Sample probe clogged", LaborCost = 1500m, PartsCost = 1200m, CreatedAt = now, IsActive = true },
                new MaintenanceRecord { Id = 6, DeviceId = 17, Type = MaintenanceType.Preventive, Title = "Biannual PM — Autoclave HS-66", ScheduledDate = now.AddDays(15), NextDueDate = now.AddDays(195), Recurrence = RecurrenceFrequency.SemiAnnually, PerformedBy = "Getinge Engineer", Status = MaintenanceStatus.Scheduled, LaborCost = 3000m, CreatedAt = now, IsActive = true },
                new MaintenanceRecord { Id = 7, DeviceId = 10, Type = MaintenanceType.Preventive, Title = "Quarterly PM — Defibrillator", ScheduledDate = now.AddDays(-15), CompletedDate = now.AddDays(-14), NextDueDate = now.AddDays(75), Recurrence = RecurrenceFrequency.Quarterly, PerformedBy = "Biomedical Team", Status = MaintenanceStatus.Completed, Findings = "Battery health 85%, pads within expiry", ActionsTaken = "Self-test passed, battery calibrated", LaborCost = 250m, CreatedAt = now, IsActive = true },
                new MaintenanceRecord { Id = 8, DeviceId = 21, Type = MaintenanceType.Preventive, Title = "Monthly PM — Dialysis Machine HD-021", ScheduledDate = now.AddDays(3), NextDueDate = now.AddDays(33), Recurrence = RecurrenceFrequency.Monthly, PerformedBy = "Fresenius Engineer", Status = MaintenanceStatus.Scheduled, LaborCost = 800m, CreatedAt = now, IsActive = true },
            });
            await ctx.SaveChangesAsync();

            // ═══════════════════════════════════════════
            // 6. CALIBRATION RECORDS (5 records)
            // ═══════════════════════════════════════════
            ctx.CalibrationRecords.AddRange(new[]
            {
                new CalibrationRecord { Id = 1, DeviceId = 1, CalibrationType = "Full Calibration", StandardUsed = "NIST-traceable dosimeter", CalibrationDate = now.AddDays(-30), NextDueDate = now.AddDays(150), PerformedBy = "Sudan Standards Bureau", IsExternalLab = true, LaboratoryName = "Sudanese Institute for Standards", Result = CalibrationResult.Pass, AsFoundData = "kVp: 118.5, mAs: 49.2", AsLeftData = "kVp: 120.0, mAs: 50.0", CertificateNumber = "SIS-2024-001", CreatedAt = now, IsActive = true },
                new CalibrationRecord { Id = 2, DeviceId = 5, CalibrationType = "Verification", StandardUsed = "Fluke ProSim 8", CalibrationDate = now.AddDays(-15), NextDueDate = now.AddDays(165), PerformedBy = "Eng. Mustafa", IsExternalLab = false, Result = CalibrationResult.Pass, AsFoundData = "All parameters within ±2%", AsLeftData = "No adjustment needed", CertificateNumber = "INT-2024-002", CreatedAt = now, IsActive = true },
                new CalibrationRecord { Id = 3, DeviceId = 29, CalibrationType = "External Calibration", StandardUsed = "Fluke reference", CalibrationDate = now.AddDays(-60), NextDueDate = now.AddDays(120), PerformedBy = "Fluke Authorized Center", IsExternalLab = true, LaboratoryName = "Fluke Calibration Center Cairo", Result = CalibrationResult.Pass, AsFoundData = "Within tolerance all ranges", AsLeftData = "No adjustment required", CertificateNumber = "FLK-2024-003", CreatedAt = now, IsActive = true },
                new CalibrationRecord { Id = 4, DeviceId = 7, CalibrationType = "Full Calibration", StandardUsed = "Calibration beads", CalibrationDate = now.AddDays(-20), NextDueDate = now.AddDays(160), PerformedBy = "Mindray Engineer", IsExternalLab = true, LaboratoryName = "Mindray Calibration Lab", Result = CalibrationResult.Pass, AsFoundData = "WBC ±0.1, RBC ±0.05, HGB ±0.3", AsLeftData = "Adjusted WBC to ±0.05", CertificateNumber = "MR-2024-004", CreatedAt = now, IsActive = true },
                new CalibrationRecord { Id = 5, DeviceId = 10, CalibrationType = "Energy Verification", StandardUsed = "Fluke DA-30", CalibrationDate = now.AddDays(-10), NextDueDate = now.AddDays(170), PerformedBy = "Eng. Hassan", IsExternalLab = false, Result = CalibrationResult.Pass, AsFoundData = "Energy: 149.5J @ 150J setting", AsLeftData = "Energy: 150.1J @ 150J setting", CertificateNumber = "INT-2024-005", CreatedAt = now, IsActive = true },
            });
            await ctx.SaveChangesAsync();

            // ═══════════════════════════════════════════
            // 7. SPARE PARTS (10 items)
            // ═══════════════════════════════════════════
            ctx.SpareParts.AddRange(new[]
            {
                new SparePart { Id = 1, PartNumber = "SP-XR-001", PartName = "X-Ray Tube Assembly (Siemens)", DeviceId = 1, Category = "Imaging Components", SupplierId = 1, SupplierName = "Siemens Healthineers", CurrentStock = 1, MinimumStock = 1, MaximumStock = 2, ReorderPoint = 1, UnitCost = 35000m, StorageLocation = "Warehouse A, Shelf 1", IsCritical = true, CreatedAt = now, IsActive = true },
                new SparePart { Id = 2, PartNumber = "SP-PM-002", PartName = "Patient Monitor ECG Cable Set", DeviceId = 5, Category = "Cables", SupplierId = 4, SupplierName = "Philips Healthcare", CurrentStock = 5, MinimumStock = 3, MaximumStock = 10, ReorderPoint = 4, UnitCost = 350m, StorageLocation = "Warehouse B, Shelf 2", IsCritical = true, CreatedAt = now, IsActive = true },
                new SparePart { Id = 3, PartNumber = "SP-IP-003", PartName = "Infusion Pump Stepper Motor", DeviceId = 6, Category = "Motors", SupplierName = "MedTech Sudan", CurrentStock = 4, MinimumStock = 3, MaximumStock = 6, ReorderPoint = 3, UnitCost = 520m, StorageLocation = "Warehouse B, Shelf 3", IsCritical = true, CreatedAt = now, IsActive = true },
                new SparePart { Id = 4, PartNumber = "SP-VM-004", PartName = "Ventilator HEPA Filter", DeviceId = 4, Category = "Filters", SupplierId = 5, SupplierName = "Dräger Medical", CurrentStock = 20, MinimumStock = 15, MaximumStock = 40, ReorderPoint = 18, UnitCost = 65m, StorageLocation = "Warehouse A, Shelf 4", IsCritical = true, CreatedAt = now, IsActive = true },
                new SparePart { Id = 5, PartNumber = "SP-DF-005", PartName = "Defibrillator Li-ion Battery", DeviceId = 10, Category = "Batteries", SupplierId = 4, SupplierName = "Philips Healthcare", CurrentStock = 3, MinimumStock = 2, MaximumStock = 5, ReorderPoint = 2, UnitCost = 1200m, StorageLocation = "Charger Station ER", IsCritical = true, CreatedAt = now, IsActive = true },
                new SparePart { Id = 6, PartNumber = "SP-AC-006", PartName = "Autoclave Door Seal Gasket", DeviceId = 17, Category = "Seals", SupplierId = 1, SupplierName = "Siemens Healthineers", CurrentStock = 3, MinimumStock = 2, MaximumStock = 5, ReorderPoint = 2, UnitCost = 280m, StorageLocation = "CSSD Storage", IsCritical = true, CreatedAt = now, IsActive = true },
                new SparePart { Id = 7, PartNumber = "SP-HD-007", PartName = "Dialyzer Dialyzer Cap", DeviceId = 21, Category = "Dialysis Consumables", SupplierId = 6, SupplierName = "Fresenius Medical Care", CurrentStock = 50, MinimumStock = 30, MaximumStock = 100, ReorderPoint = 40, UnitCost = 15m, StorageLocation = "Dialysis Storage", IsCritical = true, CreatedAt = now, IsActive = true },
                new SparePart { Id = 8, PartNumber = "SP-IB-008", PartName = "Incubator Heater Element", DeviceId = 24, Category = "Heating Elements", SupplierId = 5, SupplierName = "Dräger Medical", CurrentStock = 2, MinimumStock = 1, MaximumStock = 3, ReorderPoint = 1, UnitCost = 850m, StorageLocation = "NICU Supply", IsCritical = true, CreatedAt = now, IsActive = true },
                new SparePart { Id = 9, PartNumber = "SP-ES-009", PartName = "Electrosurgical Pencil (Disposable ×10)", DeviceId = 14, Category = "Consumables", SupplierName = "MedTech Sudan", CurrentStock = 25, MinimumStock = 10, MaximumStock = 50, ReorderPoint = 15, UnitCost = 45m, StorageLocation = "OR Supply Room", IsCritical = false, CreatedAt = now, IsActive = true },
                new SparePart { Id = 10, PartNumber = "SP-CT-010", PartName = "CT Scanner X-Ray Tube", DeviceId = 2, Category = "Imaging Components", SupplierId = 2, SupplierName = "GE Healthcare", CurrentStock = 1, MinimumStock = 1, MaximumStock = 1, ReorderPoint = 1, UnitCost = 95000m, StorageLocation = "Radiology Vault", IsCritical = true, CreatedAt = now, IsActive = true },
            });
            await ctx.SaveChangesAsync();

            // ═══════════════════════════════════════════
            // 8. SERVICE CONTRACTS (4 contracts)
            // ═══════════════════════════════════════════
            ctx.ServiceContracts.AddRange(new[]
            {
                new ServiceContract { Id = 1, ContractNumber = "SC-2024-001", ContractName = "Siemens Imaging PM Contract", SupplierId = 1, Provider = "Siemens Healthineers", ContactPerson = "Karim Mansour", StartDate = new DateTime(2024,1,1), EndDate = new DateTime(2026,12,31), AutoRenew = true, CoverageDescription = "Full preventive & corrective for X-Ray and CT", ContractValue = 85000m, ResponseTimeHours = 24, ResolutionTimeHours = 72, TotalCalls = 8, CompletedCalls = 7, SatisfactionScore = 4.5m, Status = ContractStatus.Active, CreatedAt = now, IsActive = true },
                new ServiceContract { Id = 2, ContractNumber = "SC-2024-002", ContractName = "Fresenius Dialysis Service Agreement", SupplierId = 6, Provider = "Fresenius Medical Care", ContactPerson = "Youssef Taha", StartDate = new DateTime(2024,3,1), EndDate = new DateTime(2026,2,28), AutoRenew = false, CoverageDescription = "Monthly PM, 24/7 emergency support for 3 dialysis machines", ContractValue = 42000m, ResponseTimeHours = 4, ResolutionTimeHours = 12, TotalCalls = 24, CompletedCalls = 22, SatisfactionScore = 4.2m, Status = ContractStatus.Active, CreatedAt = now, IsActive = true },
                new ServiceContract { Id = 3, ContractNumber = "SC-2024-003", ContractName = "Dräger ICU Equipment Maintenance", SupplierId = 5, Provider = "Dräger Medical", ContactPerson = "Hans Mueller", StartDate = new DateTime(2024,6,1), EndDate = new DateTime(2027,5,31), AutoRenew = true, CoverageDescription = "Ventilators, incubators, monitors — comprehensive PM", ContractValue = 65000m, ResponseTimeHours = 8, ResolutionTimeHours = 24, TotalCalls = 12, CompletedCalls = 10, SatisfactionScore = 4.8m, Status = ContractStatus.Active, CreatedAt = now, IsActive = true },
                new ServiceContract { Id = 4, ContractNumber = "SC-2024-004", ContractName = "Mindray Lab Equipment Support", SupplierId = 3, Provider = "Mindray Medical", ContactPerson = "Li Wei", StartDate = new DateTime(2024,8,1), EndDate = new DateTime(2026,7,31), AutoRenew = true, CoverageDescription = "Hematology & ultrasound maintenance", ContractValue = 28000m, ResponseTimeHours = 48, ResolutionTimeHours = 96, TotalCalls = 6, CompletedCalls = 5, SatisfactionScore = 4.0m, Status = ContractStatus.Active, CreatedAt = now, IsActive = true },
            });
            await ctx.SaveChangesAsync();

            System.Diagnostics.Debug.WriteLine($"[Seeder] Seeded: 12 departments, 1 admin, 8 suppliers, 42 devices, 8 maintenance, 5 calibration, 10 parts, 4 contracts");
            }
        }
    }
}

