version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: mems-app
    restart: unless-stopped
    ports:
      - "80:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
    volumes:
      - sqlite_data:/app

volumes:
  sqlite_data:
