// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MomenMedmSys.Data;

#nullable disable

namespace MomenMedmSys.Data.Migrations
{
    [DbContext(typeof(MedMsysDbContext))]
    partial class MedMsysDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("MomenMedmSys.Core.Entities.AssignedDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignmentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignmentNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StaffMemberId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("StaffMemberId", "DeviceId");

                    b.ToTable("AssignedDevices");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.CalibrationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccreditationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdjustmentDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AdjustmentsMade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AsFoundData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AsLeftData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Attachments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CalibrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CalibrationProcedure")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CalibrationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ElectricalSafetyTestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnvironmentalConditions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Humidity")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExternalLab")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LaboratoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementUncertainty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextDueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PerformedByStaffId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StandardCertificate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StandardUsed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TechnicianSignature")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToleranceLimits")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalibrationDate");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ElectricalSafetyTestId");

                    b.HasIndex("NextDueDate");

                    b.HasIndex("PerformedByStaffId");

                    b.ToTable("CalibrationRecords");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveDeviceCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Budget")
                        .HasColumnType("TEXT");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Floor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentCode")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.DeviceActionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NetworkDeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActionType");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("NetworkDeviceId");

                    b.HasIndex("Result");

                    b.ToTable("DeviceActionLogs");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.DeviceDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocumentType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCurrentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "DocumentType");

                    b.ToTable("DeviceDocuments");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.ElectricalSafetyTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Attachments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EarthResistanceLimit")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EarthResistanceMeasured")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InsulationResistanceLimit")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InsulationResistanceMeasured")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExternalTester")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LeakageCurrentLimit")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LeakageCurrentMeasured")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextDueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("OverallResult")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TechnicianSignature")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TestDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestEquipmentCalibration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TestEquipmentUsed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TestStandard")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TestType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestingCompany")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TouchCurrentLimit")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TouchCurrentMeasured")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisualInspectionNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("VisualInspectionPass")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("NextDueDate");

                    b.HasIndex("TestDate");

                    b.ToTable("ElectricalSafetyTests");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.MaintenanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionsTaken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Attachments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("DowntimeHours")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EstimatedCompletionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Findings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExternalContractor")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LaborCost")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("NextDueDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PartsCost")
                        .HasColumnType("REAL");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PerformedByStaffId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Recommendations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Recurrence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecurrenceInterval")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RootCause")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VerificationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("VerificationPerformed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VerifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("WorkOrderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("PerformedByStaffId");

                    b.HasIndex("ScheduledDate");

                    b.ToTable("MaintenanceRecords");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.MedicalDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcquisitionMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetTagNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AssignedStaffId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CommissioningDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CurrentDepreciatedValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepreciationMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DisposalDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisposalReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EstimatedLifespanYears")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpectedDisposalDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Floor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InstallationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastCalibrationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastMaintenanceDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSafetyTestDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaintenanceManualPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NetworkConnected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperationalManualPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PowerRequirements")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("REAL");

                    b.Property<string>("RFIDTag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegulatoryClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresCalibration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresElectricalSafetyTesting")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresPreventiveMaintenance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RiskClassification")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SafetyNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoftwareVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TechnicalSpecs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalMaintenanceCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("UdiCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WarrantyCertificatePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WarrantyExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("WarrantyProvider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WarrantyTerms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedStaffId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("SerialNumber");

                    b.HasIndex("SupplierId");

                    b.ToTable("MedicalDevices");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.NetworkDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveConnections")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthenticationMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificateExpiry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConnectionStatus")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CpuUsage")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DiscoveredVia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiscoveryProtocol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("DiskUsage")
                        .HasColumnType("REAL");

                    b.Property<string>("DnsServer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorLogs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("FirewallEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirmwareVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstDiscovered")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gateway")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastErrorTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<string>("ManagementPort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ManagementProtocol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MedicalDeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MemoryUsage")
                        .HasColumnType("REAL");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("NetworkBandwidthUsage")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenPorts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RemoteAccessUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RemoteManagementEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoftwareVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SslEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubnetMask")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SupportsRemoteConfiguration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsRemoteDiagnostics")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsRemoteReboot")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsRemoteUpdate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemHealthStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UptimeHours")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionStatus");

                    b.HasIndex("DeviceName");

                    b.HasIndex("Hostname");

                    b.HasIndex("IpAddress");

                    b.HasIndex("MacAddress");

                    b.HasIndex("MedicalDeviceId");

                    b.ToTable("NetworkDevices");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.ProcurementRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualDeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovalNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BudgetApproved")
                        .HasColumnType("REAL");

                    b.Property<decimal>("BudgetEstimate")
                        .HasColumnType("REAL");

                    b.Property<string>("BudgetSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClinicalNeed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedDeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EquipmentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EstimatedPatientVolume")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpectedDeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FundingSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GapAnalysis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InstallationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MinimumRequirements")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredBrands")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PurchaseOrderNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SelectedSupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectionJustification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TechnicalSpecifications")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDeviceId");

                    b.HasIndex("RequestNumber")
                        .IsUnique();

                    b.HasIndex("SelectedSupplierId");

                    b.HasIndex("Status");

                    b.ToTable("ProcurementRequests");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.RiskIncident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActionDeadline")
                        .HasColumnType("TEXT");

                    b.Property<int>("AffectedPatients")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AffectedStaff")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Attachments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectiveActions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IncidentCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IncidentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IncidentLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InjuryDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InvestigationCompleteDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvestigationFindings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRecall")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PatientInjury")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatientsInvolved")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreventiveActions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Probability")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecallAuthority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RecallDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecallNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RegulatoryReportDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegulatoryReportReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RegulatoryReported")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RootCause")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StaffInjury")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StaffMembersInvolved")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("IncidentCode")
                        .IsUnique();

                    b.HasIndex("IncidentDate");

                    b.ToTable("RiskIncidents");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.ServiceContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Attachments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletedCalls")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ContractValue")
                        .HasColumnType("REAL");

                    b.Property<string>("CoverageDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoveredDeviceCategories")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoveredDeviceIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentTerms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PenaltyClause")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RenewalNoticeDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RenewalNoticeDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResolutionTimeHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResponseTimeHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SLADetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SatisfactionScore")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalCalls")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WarrantyCertificatePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContractNumber")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("ServiceContracts");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.SparePart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompatibleModels")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsObsolete")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LastOrderCost")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastOrderDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaximumStock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReorderPoint")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalUsageCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("PartNumber")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("SpareParts");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.SparePartUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaintenanceRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SparePartId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UsedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaintenanceRecordId");

                    b.HasIndex("SparePartId");

                    b.ToTable("SparePartUsages");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.StaffMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanAccessAdminPanel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanManageCalibration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanManageDevices")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanManageMaintenance")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanManageNetworkDevices")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanManageSpareParts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanManageStaff")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanViewReports")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Certifications")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActiveAccount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LicenseExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("StaffMembers");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OnTimeDeliveries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentTerms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCategories")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalOrders")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SupplierCode")
                        .IsUnique();

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.TechnicalEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeliveryTimeframe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Deviations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EvaluatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EvaluationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvaluationNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FinancialScore")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentTerms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcurementRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QualityScore")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("QuotedPrice")
                        .HasColumnType("REAL");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupportScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TechnicalCompliance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TechnicalScore")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalCostOfOwnership")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WarrantyYears")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.HasIndex("ProcurementRequestId", "SupplierId");

                    b.ToTable("TechnicalEvaluations");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.TrainingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AssessmentPassed")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AssessmentScore")
                        .HasColumnType("TEXT");

                    b.Property<string>("AttachmentPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StaffMemberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Trainer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TrainingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrainingDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrainingProvider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrainingTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("StaffMemberId", "DeviceId", "TrainingDate");

                    b.ToTable("TrainingRecords");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ActualCost")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActualStartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AssignedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Attachments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("FaultDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExternalContractor")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaintenanceRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResolutionTimeHours")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResponseTimeHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RootCause")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SLADeadline")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ScheduledEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ScheduledStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkOrderNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("MaintenanceRecordId")
                        .IsUnique();

                    b.HasIndex("ReportDate");

                    b.HasIndex("Status");

                    b.HasIndex("WorkOrderNumber")
                        .IsUnique();

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.AssignedDevice", b =>
                {
                    b.HasOne("MomenMedmSys.Core.Entities.MedicalDevice", "Device")
                        .WithMany("AssignedDevices")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MomenMedmSys.Core.Entities.StaffMember", "StaffMember")
                        .WithMany("AssignedDevices")
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("StaffMember");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.CalibrationRecord", b =>
                {
                    b.HasOne("MomenMedmSys.Core.Entities.MedicalDevice", "Device")
                        .WithMany("CalibrationRecords")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MomenMedmSys.Core.Entities.ElectricalSafetyTest", "ElectricalSafetyTest")
                        .WithMany()
                        .HasForeignKey("ElectricalSafetyTestId");

                    b.HasOne("MomenMedmSys.Core.Entities.StaffMember", "PerformedByStaff")
                        .WithMany()
                        .HasForeignKey("PerformedByStaffId");

                    b.Navigation("Device");

                    b.Navigation("ElectricalSafetyTest");

                    b.Navigation("PerformedByStaff");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.DeviceActionLog", b =>
                {
                    b.HasOne("MomenMedmSys.Core.Entities.NetworkDevice", "NetworkDevice")
                        .WithMany("ActionLogs")
                        .HasForeignKey("NetworkDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NetworkDevice");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.DeviceDocument", b =>
                {
                    b.HasOne("MomenMedmSys.Core.Entities.MedicalDevice", "Device")
                        .WithMany("Documents")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.ElectricalSafetyTest", b =>
                {
                    b.HasOne("MomenMedmSys.Core.Entities.MedicalDevice", "Device")
                        .WithMany("SafetyTests")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.MaintenanceRecord", b =>
                {
                    b.HasOne("MomenMedmSys.Core.Entities.MedicalDevice", "Device")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MomenMedmSys.Core.Entities.StaffMember", "PerformedByStaff")
                        .WithMany()
                        .HasForeignKey("PerformedByStaffId");

                    b.Navigation("Device");

                    b.Navigation("PerformedByStaff");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.MedicalDevice", b =>
                {
                    b.HasOne("MomenMedmSys.Core.Entities.StaffMember", "AssignedStaff")
                        .WithMany()
                        .HasForeignKey("AssignedStaffId");

                    b.HasOne("MomenMedmSys.Core.Entities.Department", "DepartmentEntity")
                        .WithMany("Devices")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("MomenMedmSys.Core.Entities.Supplier", "SupplierEntity")
                        .WithMany("SuppliedDevices")
                        .HasForeignKey("SupplierId");

                    b.Navigation("AssignedStaff");

                    b.Navigation("DepartmentEntity");

                    b.Navigation("SupplierEntity");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.NetworkDevice", b =>
                {
                    b.HasOne("MomenMedmSys.Core.Entities.MedicalDevice", "MedicalDevice")
                        .WithMany()
                        .HasForeignKey("MedicalDeviceId");

                    b.Navigation("MedicalDevice");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.ProcurementRequest", b =>
                {
                    b.HasOne("MomenMedmSys.Core.Entities.MedicalDevice", "CreatedDevice")
                        .WithMany()
                        .HasForeignKey("CreatedDeviceId");

                    b.HasOne("MomenMedmSys.Core.Entities.Supplier", "SelectedSupplier")
                        .WithMany("ProcurementRequests")
                        .HasForeignKey("SelectedSupplierId");

                    b.Navigation("CreatedDevice");

                    b.Navigation("SelectedSupplier");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.RiskIncident", b =>
                {
                    b.HasOne("MomenMedmSys.Core.Entities.MedicalDevice", "Device")
                        .WithMany("RiskIncidents")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.ServiceContract", b =>
                {
                    b.HasOne("MomenMedmSys.Core.Entities.Supplier", "Supplier")
                        .WithMany("Contracts")
                        .HasForeignKey("SupplierId");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.SparePart", b =>
                {
                    b.HasOne("MomenMedmSys.Core.Entities.MedicalDevice", "Device")
                        .WithMany("SpareParts")
                        .HasForeignKey("DeviceId");

                    b.HasOne("MomenMedmSys.Core.Entities.Supplier", "SupplierEntity")
                        .WithMany("SuppliedParts")
                        .HasForeignKey("SupplierId");

                    b.Navigation("Device");

                    b.Navigation("SupplierEntity");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.SparePartUsage", b =>
                {
                    b.HasOne("MomenMedmSys.Core.Entities.MaintenanceRecord", "MaintenanceRecord")
                        .WithMany("SparePartUsages")
                        .HasForeignKey("MaintenanceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MomenMedmSys.Core.Entities.SparePart", "SparePart")
                        .WithMany("Usages")
                        .HasForeignKey("SparePartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaintenanceRecord");

                    b.Navigation("SparePart");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.StaffMember", b =>
                {
                    b.HasOne("MomenMedmSys.Core.Entities.Department", "DepartmentEntity")
                        .WithMany("StaffMembers")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("DepartmentEntity");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.TechnicalEvaluation", b =>
                {
                    b.HasOne("MomenMedmSys.Core.Entities.ProcurementRequest", "ProcurementRequest")
                        .WithMany("TechnicalEvaluations")
                        .HasForeignKey("ProcurementRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MomenMedmSys.Core.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcurementRequest");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.TrainingRecord", b =>
                {
                    b.HasOne("MomenMedmSys.Core.Entities.MedicalDevice", "Device")
                        .WithMany("TrainingRecords")
                        .HasForeignKey("DeviceId");

                    b.HasOne("MomenMedmSys.Core.Entities.StaffMember", "StaffMember")
                        .WithMany("TrainingRecords")
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("StaffMember");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.WorkOrder", b =>
                {
                    b.HasOne("MomenMedmSys.Core.Entities.MedicalDevice", "Device")
                        .WithMany("WorkOrders")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MomenMedmSys.Core.Entities.MaintenanceRecord", "MaintenanceRecord")
                        .WithOne("WorkOrder")
                        .HasForeignKey("MomenMedmSys.Core.Entities.WorkOrder", "MaintenanceRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Device");

                    b.Navigation("MaintenanceRecord");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.Department", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("StaffMembers");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.MaintenanceRecord", b =>
                {
                    b.Navigation("SparePartUsages");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.MedicalDevice", b =>
                {
                    b.Navigation("AssignedDevices");

                    b.Navigation("CalibrationRecords");

                    b.Navigation("Documents");

                    b.Navigation("MaintenanceRecords");

                    b.Navigation("RiskIncidents");

                    b.Navigation("SafetyTests");

                    b.Navigation("SpareParts");

                    b.Navigation("TrainingRecords");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.NetworkDevice", b =>
                {
                    b.Navigation("ActionLogs");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.ProcurementRequest", b =>
                {
                    b.Navigation("TechnicalEvaluations");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.SparePart", b =>
                {
                    b.Navigation("Usages");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.StaffMember", b =>
                {
                    b.Navigation("AssignedDevices");

                    b.Navigation("TrainingRecords");
                });

            modelBuilder.Entity("MomenMedmSys.Core.Entities.Supplier", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("ProcurementRequests");

                    b.Navigation("SuppliedDevices");

                    b.Navigation("SuppliedParts");
                });
#pragma warning restore 612, 618
        }
    }
}
